### ISSUE TITLE
Widget usage

### ISSUE THREAD

**Issue by obitohub** [surveyjs/widgets#1]
Hi,

are these widgets working ? And if so how to implement into angular2 app ? In package.json I included "surveyjs-widgets": "^0.12.55" and for question it is:
{
  "type": "datepicker",
  "name": "Q31C",
  "title": "Reporting Date"
}

If its working what else is missing ? And could you please write an example ?

**Comment by dmitrykurmanov** [comment]
We are working on release with new custom widgets. So it is in development and we have an examples only for ReactJS yet. But I think that it provides main idea of usage. Could you please check: https://stackblitz.com/edit/surveyjs-widgets-react ?

P.S.

Please pay attention to index.js file and global jQuery 
```
    import ('jquery-ui/ui/widgets/datepicker.js');
    window["$"] = window["jQuery"] = $;
```
this is because of jquery datepicker is not a umd build.

**Comment by dmitrykurmanov** [comment]
and if you know the best way to use jquery UI datepicker with es modules it would be great to share with us

**Comment by sfcrebecca** [comment]
I am using Angular 5 and have installed `"surveyjs-widgets": "^0.96.1"` and add all the widget JS files in `.angular-cli.json`

```
"scripts": [
            "../node_modules/jquery/dist/jquery.js",
            "../node_modules/jquery/dist/jquery.slim.js",
            "../node_modules/survey-jquery/survey.jquery.js",
            "../node_modules/surveyjs-widgets/surveyjs-widgets.js",
            "../node_modules/select2/dist/js/select2.js",
            "../node_modules/select2/dist/js/select2.full.js",
            "../node_modules/inputmask/dist/jquery.inputmask.bundle.js",
            "../node_modules/inputmask/dist/inputmask/phone-codes/phone.js",
            "../node_modules/surveyjs-widgets/widgets/ck-editor.js",
            "../node_modules/surveyjs-widgets/widgets/icheck.js",
            "../node_modules/surveyjs-widgets/widgets/image-picker.js",
            "../node_modules/surveyjs-widgets/widgets/jquery-bar-rating.js",
            "../node_modules/surveyjs-widgets/widgets/jquery-ui-datepicker.js",
            "../node_modules/surveyjs-widgets/widgets/nouislider.js",
            "../node_modules/surveyjs-widgets/widgets/select2-tagbox.js",
            "../node_modules/surveyjs-widgets/widgets/signature_pad.js",
            "../node_modules/surveyjs-widgets/widgets/sortablejs.js"
```

However, I still can't have these widgets working. Am I missing any steps or they are not supported in Angular5?

**Comment by dmitrykurmanov** [comment]
@sfcrebecca, do you check the examples https://stackblitz.com/edit/surveyjs-widgets-react ?

**Comment by sfcrebecca** [comment]
@dmitrykurmanov,

Yes I have read through the examples provided by surveyjs and in Github. However, none of them shows how to put these components in Angular's framework.

In my Angular project, I just render the survey by defining the components in a JSON file. It is a mix of standard and customized widgets. 

```
E.g. 
     {
          "isRequired": true,
          "name": "name",
          "type": "text",
          "title": "Please enter your company name"
     },
     {
        "type": "dropdown",
        "renderAs": "select2",
        "choicesByUrl": {
          "url": "https://restcountries.eu/rest/v1/all"
        },
        "name": "countries",
        "title": "Please provide the place of incorporation:"
     },
    {
      "type": "editor",
      "name": "wysiwyg_editor",
      "title": "WYSIWYG Editor"
    }, 
```
Then, I will define a SurveyComponent:

```
@Component({
  selector: 'app-survey',
  templateUrl: './survey.component.html',
  styleUrls: ['./survey.component.css'],
  providers: [HttpService]
})

export class SurveyComponent implements OnInit, OnDestroy ....
```

Next, I will create the Survey object by 

`let _surveyModel = new Survey.ReactSurveyModel(<json>);`

and render it by:

```
    Survey.SurveyNG.render(
        'surveyElement', 
        { model: surveyModel }
    );
```

It has been working for those standard components. 

However, when I simply add the custom widgets in the JSON, the above approach simply ignore those tag. For example, when I specify a `select2` component, it just renders a normal `dropdown `component, and the for the rest, it simply generates nothing.

So I would like to know the steps to let Angular know about these component.

Do I need to put the following somewhere in my project? 


```
import $ from 'jquery';

import Select2Widget from './components/Select2Widget';
import ImagePickerWidget from './components/ImagePickerWidget';
import ICheckWidget from './components/ICheckWidget';
import InputmaskWidget from './components/InputmaskWidget';
import JQueryBarRating from './components/JQueryBarRating';
import JqueryUiDatepicker from './components/JqueryUiDatepicker';
import Nouislider from './components/Nouislider';
import Select2TagboxWidget from './components/Select2TagboxWidget';
import Signaturepad from './components/Signaturepad';
import Sortablejs from './components/Sortablejs';

import 'bootstrap/dist/css/bootstrap.css'
import './style.css';
```

Your guidance in this matter is greatly appreciated.

**Comment by dmitrykurmanov** [comment]
you need to initialize widget and select2 as in this file: https://stackblitz.com/edit/surveyjs-widgets-react?file=components%2FSelect2Widget.js

```
import $ from 'jquery'; 
import select2Init from 'select2';
import * as Survey from 'survey-react';
import * as widgets from 'surveyjs-widgets';

select2Init();
widgets.select2(Survey);
...
var model = new Survey.Model(json);    
```

**Comment by dmitrykurmanov** [comment]
> I suppose that when I put them under "scripts" in .angular_cli.json, they will got executed and being recognized by Angular.

this is the better scenario and we think about it, but now we need to initialize widget separately
