### ISSUE TITLE
404...

### ISSUE THREAD

**Issue by Adrion** [surveyjs/widgets#101]
https://unpkg.com/surveyjs-widgets => 404

https://unpkg.com/surveyjs-widgets@1.0.61/index.js => 404

Did you removed it from unpkg ?

**Comment by tsv2013** [comment]
This issue is not related to SurveyJS
We are ok on the NPM
But there is a bug in unpkg - https://github.com/unpkg/unpkg.com/issues/156

**Comment by tsv2013** [comment]
You can use direct unpkg link - https://unpkg.com/surveyjs-widgets/surveyjs-widgets.js

**Comment by Adrion** [comment]
Wow bigger issue than I thought ! 
Thanks for the info. 

I'll use the azure CDN instead :)
