### ISSUE TITLE
noUISlider isRequired check doesn't work

### ISSUE THREAD

**Issue by carstenbaumhoegger** [surveyjs/widgets#102]
Hello!
We're currently developing a software that is using SurveyJS to do the survey heavy-lifting.
We're using `noUiSlider` for some questions and need these questions to be answered, so we set them to be required.
When we select the noUiSlider in SurveyJS Builder we set the default value to be empty. So we expect the isRequired check not to pass.
When you start the survey, the value of the slider is "50", so the `isRequired` check doesn't work. The user can just skip through the questions without being forced to answer the questions using `noUiSlider`. We're expecting the initial value to be null or empty and only be filled when the user moves the slider so that the `isRequired` check is working correctly.

How can we accomplish this?

**Comment by dmitrykurmanov** [comment]
I've fixed the problem via the https://github.com/surveyjs/widgets/commit/be1d4683ba77c6c25e77a4106ffeee18779b96ef . Fix will be available in the next minor update (most likely tomorrow).

As for ui bug. We can fix it via the additional css:
```css
.sv_q.sv_qstn .noUi-horizontal .noUi-tooltip {
  bottom: -130%;
}
```

Here the working example with the latest build: https://plnkr.co/edit/c3ubViOWkRhujldpV8Bb?p=preview

**Comment by carstenbaumhoegger** [comment]
hey @dmitrykurmanov ,
thank you for fixing this, works like a charm!
