### ISSUE TITLE
React onCurrentPageChanged and prettycheckbox issue 

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/widgets#104]
related to https://github.com/surveyjs/surveyjs/issues/1504#issuecomment-453527085

> I found the issue source: widgets.prettycheckbox(Survey, $);
After applying this code onCurrentPageChanged method (maybe and another too) works incorrectly.
So widgets affects working of survey

**Comment by dmitrykurmanov** [comment]
@stsiushkevich I've created an example with prettycheckbox and  `onCurrentPageChanged ` event https://plnkr.co/edit/t83Cm57wN6CMv37AdppA?p=preview and it looks ok. Could you check it please?

**Comment by stsiushkevich** [comment]
> @stsiushkevich I've created an example with prettycheckbox and `onCurrentPageChanged ` event https://plnkr.co/edit/t83Cm57wN6CMv37AdppA?p=preview and it looks ok. Could you check it please?

Yes, it works fine.
