### ISSUE TITLE
Add select2 api widget

### ISSUE THREAD

**Issue by willgdjones** [surveyjs/widgets#107]
### Are you requesting a feature, reporting a bug or asking a question?

Asking a question

### What is the current behavior?

I cannot pass parameters from surveys into my custom widgets

### What is the expected behavior?

I would like to be able to pass a 'url' parameter, but I am unable to do so.

### How would you reproduce the current behavior (if this is a bug)?

Take a look at this LOC: https://github.com/willgdjones/widgets/blob/master/src/select2-tagbox-medical.js#L43

I have had to hard code this, but I want to pass it from 'question'.

* browser: Chrome
* browser version: Version 71.0.3578.98 (Official Build)
* surveyjs platform (angular or react or jquery or knockout or vue): Vue
* surveyjs version: 1.0.68

**Comment by tsv2013** [comment]
@willgdjones I've transferred this question into the corresponding repo

**Comment by tsv2013** [comment]
I beleive you can use the `select2Config` option, as described in this thread - https://github.com/surveyjs/widgets/issues/97

**Comment by willgdjones** [comment]
Hi @tsv2013 - I don't think that solution will work because I've had to include the select2Config in the package definition since it does not contain valid JSON.

Ideally, there would be a question parameter that I can access from inside `question` within the `afterRender` method: https://github.com/willgdjones/widgets/blob/master/src/select2-tagbox-medical.js#L43

**Comment by dmitrykurmanov** [comment]
@willgdjones hello! Thank you for the interest and contributing! 

I am sorry but I don't understand your use case. Could you please clarify it? 

As for me `select2Config` looks ok, here the example with your ajax call to stackoverflow:
https://plnkr.co/edit/px5lgRy3m8k8brnkiMTp?p=preview

**Comment by willgdjones** [comment]
Hi @dmitrykurmanov! Thanks for the response.

The definition of my survey needs to be valid JSON. And so I have created new widgets with the functionality I want in my repo. The select2configs that you have listed, while being very helpful, unfortunately, cannot be pasted into the survey builder.

Also, the surveys that you link to in your plunker seem to only return the ids in the question id, whereas it would be much more helpful if they returned the choice. Is there a way to do this?

E.g. for your stackoverflow example, you return the links.

<img width="1067" alt="screenshot 2019-02-12 at 15 30 20" src="https://user-images.githubusercontent.com/1719848/52646724-2da4c780-2edb-11e9-8dd5-49cc869ebe1f.png">

**Comment by willgdjones** [comment]
Additionally, I am not able to display existing data in the same way that I am able to in this example, e.g. with the data: 'Andorra'. It would be great to find a way to do that! Thanks a lot, I've been trying to for a little while now but I haven't been able to find a solution. https://surveyjs.io/Examples/Library/?id=custom-widget-select2-tagbox&platform=jQuery&theme=default

**Comment by willgdjones** [comment]
Ok - I have now found a solution to the first issue. Basically setting the id as the text itself:
https://plnkr.co/edit/DkI2Zntde7FQS4yeuZm1?p=preview

However, I still need to find a way to feed in existing data to the survey response. It seems possible to do that when the choices are specified in the survey definition itself either explicitly or by url, but if the choices are retrieved by API, it is not possible.

**Comment by willgdjones** [comment]
Hi @dmitrykurmanov - I just took another look at it and it definitely seems to be some missing functionality in the widget itself. I would be happy to talk it over and add the functionality myself but I think I need some advice to do it! Thanks

**Comment by willgdjones** [comment]
Hi guys @andrewtelnov  - sorry to bother you on just. Just would be good to get a couple of thoughts I would be happy to do the heavy development work.

**Comment by andrewtelnov** [comment]
Hi,
We will discuss it tomorrow.

Thank you,
Andrew

**Comment by willgdjones** [comment]
Hi @andrewtelnov - thanks!

**Comment by willgdjones** [comment]
@andrewtelnov Let me know if you need any more clarifications/information from me!

**Comment by andrewtelnov** [comment]
@willgdjones We have discussed it today. @dmitrykurmanov made an example, he will post it shortly.

Thank you,
Andrew

**Comment by willgdjones** [comment]
@andrewtelnov Thanks very much!

**Comment by dmitrykurmanov** [comment]
@willgdjones  if I understand you correctly you need to set default data with select2 and ajax. And it seems that it is not working now. Here an example https://plnkr.co/edit/ZgG7zSCFVI6Y6YxEeUi1?p=preview I will investigate the problem. Thanks

**Comment by willgdjones** [comment]
@dmitrykurmanov Yes that's right. Thank you!

**Comment by dmitrykurmanov** [comment]
@willgdjones I've made some changed according to select2 documentation. 

Please check this example https://plnkr.co/edit/7Sw6Jqxjdt54CknWyLWp?p=preview with the latest build. Does it cover your needs?

**Comment by willgdjones** [comment]
Hi @dmitrykurmanov thank you for your work on this. I am just thinking how to modify your code so that it is applicable for the tagbox!

**Comment by willgdjones** [comment]
I didn't post that message above when a wrote it a few days ago. How would I modify the tagbox widget examples to behave in the same way?

**Comment by willgdjones** [comment]
I managed to modify your example to make it work with tagbox - thanks for all of your help @andrewtelnov @dmitrykurmanov @tsv2013 https://plnkr.co/edit/DkI2Zntde7FQS4yeuZm1?p=preview
