### ISSUE TITLE
Signaturepad leading to CORS errors (Safari browser)

### ISSUE THREAD

**Issue by StephanMeijer** [surveyjs/widgets#108]
Related:
- https://stackoverflow.com/questions/25753754/canvas-todataurl-security-error-the-operation-is-insecure
- https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

### Are you requesting a feature, reporting a bug or asking a question?

Bug.

### What is the current behavior?

It is unable to get the data in safari, possibly because the [cross-origin attribute has not been set on the canvas-element](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image)

### What is the expected behavior?

To correctly transform canvas data into base64-encoded date with the possibility to send the date to a server (Amazon)

### How would you reproduce the current behavior (if this is a bug)?

Signaturepad element in Safari.

#### Provide the test code and the tested page URL (if applicable)

```
            {
              type: "signaturepad",
              name: "signature",
              isRequired: true,
              title: {
                en: "Please enter your signature",
                ar: "الرجاء قم بالتوقيع في المربع في الأسفل"
              }
            },

```

Error in codebase of Surveyjs:

```
      signaturePad.onEnd = function() {
        var data = signaturePad.toDataURL();
        question.value = data;
      };
      var updateValueHandler = function() {
        var data = question.value;
        canvas.width = question.width;
        canvas.height = question.height;
        resizeCanvas(canvas);
        signaturePad.fromDataURL(
          data || "data:image/gif;base64,R0lGODlhAQABAIAAAP"
        );
      };
````

<img width="1035" alt="screenshot 2019-02-25 at 14 41 26" src="https://user-images.githubusercontent.com/3169264/53341289-77de6d80-390b-11e9-9cca-0114330afafd.png">

### Specify your

* browser: Safari (Chrome sometimes as well)
* browser version: Safari `Version 12.0.3 (14606.4.5)`
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: `1.0.71`

**Comment by tsv2013** [comment]
Moved to the corresponding repo

**Comment by StephanMeijer** [comment]
@tsv2013 Thanks

**Comment by StephanMeijer** [comment]
Resetting signature to "" fixes it on my end, but this needs to be handled by SurveyJS and not by my front-end application:
```
    this.model = new Survey.Model({
      // ..
    });
    this.model.data = {
       ...this.props.data, signature: ""
    };
```

**Comment by tsv2013** [comment]
I've not been managed to reproduce it in Chrome/Opera/Firefox

**Comment by StephanMeijer** [comment]
signature was being loaded in as URL.

**Comment by tsv2013** [comment]
I've not been managed to reproduce it in Safari on windows machine. Probably I need to try Mac. I'm using the JSON you've provided to reproduce the issue.

**Comment by StephanMeijer** [comment]
Have you been trying feeding this.model.data.signature with an url to a PNG file?

**Comment by tsv2013** [comment]
Yes, I've feeding the signaturepad with initial data, produced by the signaturepad. Here is the plunker - https://next.plnkr.co/edit/RBuJ3OJuB8GCGbuR
Does if work for you?

**Comment by tsv2013** [comment]
As for url to a PNG file - if it is really stored on other domain, I think it's ok that you aware of it via the console error. Probably you need to allow CORS on the server side as described in the article you mention - https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
