### ISSUE TITLE
CKEditor toolbar widget not working as expected

### ISSUE THREAD

**Issue by hekin1** [surveyjs/widgets#110]
When trying to add the ckeditor widget following error occurs in console of firefox 65.01 (64-bit):
```
TypeError: this.document.getWindow(...).$ is undefined[Läs mer] ckeditor.js:448:29

    getNative ckeditor.js:448 selection ckeditor.js:446 getSelection ckeditor.js:443 Image ckeditor.js:1080 save ckeditor.js:1075 init ckeditor.js:1071 n ckeditor.js:10 fire ckeditor.js:12 fire ckeditor.js:13 setData ckeditor.js:275 updateValueHandler surveyjs-widgets.js:1340 fireCallback survey.ko.js:3104 set survey.ko.js:3356 setDefaultValue survey.ko.js:3473 updateValueWithDefaults survey.ko.js:3464 onSetData survey.ko.js:3313 setSurveyImpl survey.ko.js:1833 setSurveyImpl survey.ko.js:2630 onAddElement survey.ko.js:6368 <anonym> (index):977 push survey.ko.js:1666 addElement survey.ko.js:6628 dragDropFinish survey.ko.js:10728 doDrop surveyeditor.js:6329 doDrop surveyeditor.js:6562 ondrop surveyeditor.js:6440
```
Steps to reproduce:
1. git clone https://github.com/surveyjs/surveyjs_vue_quickstart.git
2. Add `<script src="https://cdn.ckeditor.com/4.7.3/standard/ckeditor.js"></script>` to index.html `<head>` element
3. npm i
4. npm run dev
5. Open firefox (version 65.0.1 64-bit) and go to localhost:8080
6. Try to drag a ckeditor question to the surveybuilder.
7. Error is displayed in console

**Comment by andrewtelnov** [comment]
@hekin1 Please look at [this example](https://surveyjs.io/Examples/Builder/?id=ckeditorpropertyeditor).
I have just tried it on FireFox, 66 (64-bit), it works fine.

Thank you,
Andrew

**Comment by hekin1** [comment]
@andrewtelnov Yes, but I am refering to ckeditor as a toolbar widget for question types, not property editor.. Your link works OK, but thats because you use it as a question property editor.
Try using ckeditor (latest version) with surveyjs-widgets (latest version).
Best regards Henrik

**Comment by andrewtelnov** [comment]
@hekin1 Does [this example](https://surveyjs.io/Examples/Library/?id=custom-widget-ckeditor) help you?

Thank you,
Andrew

**Comment by hekin1** [comment]
@andrewtelnov Not really, because the problem is with ckeditor (later versions) not functioning properly with survejs-widgets.
The problem occurs when using ckeditor version greater than 4.3.5. (I tried all versions above and they all fail)

I didnt spend too much time investigating, but maybe it has something to do with the ckeditor iframe when manipulating the DOM.
I found this which was quite interesting
https://dev.ckeditor.com/ticket/12258
Status of this ticket is wont fix and a suggestion to use inline editor instead.

**Comment by dmitrykurmanov** [comment]
@hekin1 Hello! I've tried to reproduce it with the steps above and without success. (Chrome and Firefox)

Also I've created an example for you https://codesandbox.io/s/0y63986m4v Could you please check and modify it to reproduce the problem?

**Comment by hekin1** [comment]
Ok I recreated it with your sandbox here: https://codesandbox.io/s/zr5w26znwm
Note that the only thing I did was removing all widgets except for the ckeditor:

changed this:
```
import * as SurveyEditor from 'surveyjs-editor'
import 'surveyjs-editor/surveyeditor.css';

import * as SurveyKo from "survey-knockout";
import * as widgets from "surveyjs-widgets";

import "inputmask/dist/inputmask/phone-codes/phone.js";

widgets.icheck(SurveyKo);
widgets.select2(SurveyKo);
widgets.inputmask(SurveyKo);
widgets.jquerybarrating(SurveyKo);
widgets.jqueryuidatepicker(SurveyKo);
widgets.nouislider(SurveyKo);
widgets.select2tagbox(SurveyKo);
widgets.signaturepad(SurveyKo);
widgets.sortablejs(SurveyKo);
widgets.ckeditor(SurveyKo);
widgets.autocomplete(SurveyKo);
widgets.bootstrapslider(SurveyKo);
```

to this:
```
import * as SurveyEditor from 'surveyjs-editor'
import 'surveyjs-editor/surveyeditor.css';

import * as SurveyKo from "survey-knockout";
import * as widgets from "surveyjs-widgets";

widgets.ckeditor(SurveyKo);
```

**Comment by andrewtelnov** [comment]
@hekin1 I do not see jQuery in your import. ckEditor requires it.

Thank you,
Andrew

**Comment by hekin1** [comment]
I did not remove jQuery from the sandbox @dmitrykurmanov created. So I dont know about that.. It works fine.

**Comment by andrewtelnov** [comment]
@hekin1 Yes, you are right. We will investigate it.

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
I don't manage to reproduce this error: 

> TypeError: this.document.getWindow(...).$ is undefined[Läs mer] ckeditor.js:448:29

but anyway if we add two ckeditor's and try to drag and drop them we will see many console errors and the builder will break. I will investigate it.

**Comment by dmitrykurmanov** [comment]
@hekin1 @andrewtelnov I believe that I fixed all problems with ckEditor via the https://github.com/surveyjs/widgets/commit/688fde713a6995e482430ef4f016c9b266f9c70d . 

Fix will be available in the next minor update
