### ISSUE TITLE
tagbox in matrixdynamic cell Maximum call stack size exceeded

### ISSUE THREAD

**Issue by masciugo** [surveyjs/widgets#112]
When I use the tagbox widget in the matrixdynamic I got 

![Screen Shot 2019-03-27 at 18 12 46](https://user-images.githubusercontent.com/454321/55097373-fcafd900-50bb-11e9-992d-b7c9846adad0.png)

[here's the plunker to reproduce the error](https://plnkr.co/edit/4jSyTSnMVuTdKKU2vPE7?p=preview)

**Comment by andrewtelnov** [comment]
@masciugo What should we do to reproduct the error?

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo Sorry, I did not look at console. I can see the error.

We will work on the fix.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@masciugo The bug was in checkbox. It doesn't work correctly for matrixdynamic + checkbox + choicesFromUrl functionality. tagbox is derived from checkbox.

Anyway, I have fixed it.

Thank you,
Andrew
