### ISSUE TITLE
select2 widget and restfull choices with preloaded data

### ISSUE THREAD

**Issue by masciugo** [surveyjs/widgets#114]
After [this commit](https://github.com/surveyjs/survey-library/commit/cd3021d605286141d3103afa5c3e2fadb3b9ca92) select2 does not fill the field with preloaded data

https://next.plnkr.co/edit/wvYJNm1fdQ5LyEvM

**Comment by tsv2013** [comment]
@masciugo I see the issue.
@gologames Alexander, could you take a look?

**Comment by gologames** [comment]
Hello @masciugo,
We reverted [that commit](https://github.com/surveyjs/survey-library/commit/cd3021d605286141d3103afa5c3e2fadb3b9ca92) right now via [this commit](https://github.com/surveyjs/survey-library/commit/2c28eb3b6761e66c290b565090a86cfa77255ab0). Later we will make a more complete solution to the old problem. Your problem has been fixed
