### ISSUE TITLE
Getting No microphone error on physical device

### ISSUE THREAD

**Issue by taimoorimran** [surveyjs/widgets#115]
I am using the survey-js microphone widget with react native and getting "No Microphone" error in webView in Android physical device although it works fine when i open the localhost link on my laptop.
I thought it was a permission issue so i added the permissions for microphone in AndroidManifest.xml but still got no luck. Please help!

**Comment by tsv2013** [comment]
Unfortunately we've not tested thiese widgets on mobile devices. Probably it is better to find answers on specific forums.
