### ISSUE TITLE
1.0.85 (jquery/select2): select2 dropdown value missing

### ISSUE THREAD

**Issue by whity76** [surveyjs/widgets#117]
plunk for version 1.0.60:
https://plnkr.co/edit/Apqo32Wead3wfprmrSxO?p=preview

plunk for version 1.0.85:
https://plnkr.co/edit/GQl2e5rpFj1ugMZmRKUK?p=preview

steps in both plunks to reproduce the problem

1) search for "sql" (without "")
2) select value from dropdown, ideally the same
3) click complete

result is empty in version 1.0.85, result is present in 1.0.60.
didn't try other versions betwen .60 and .85.

**Comment by tsv2013** [comment]
We've fixed the issue
Fix will be available in the nearest update

**Comment by whity76** [comment]
Thx for your fast help!

**Comment by whity76** [comment]
Problem is here again, Last working version is 1.0.89, since 1.0.90 value is empty.

not working, please look at actual version of plunk (using 1.0.95):
https://plnkr.co/edit/msMbPudJFNgUF0NxyZV4?p=info

working, please look at previous version of plunk (using 1.0.89)

**Comment by dk981234** [comment]
Hello,
We've fixed the issue
Fix will be available in the nearest update
Thanks, Dmitry
SurveyJs Team

**Comment by whity76** [comment]
thx!
