### ISSUE TITLE
i have sortablelist but i want user select only one thing

### ISSUE THREAD

**Issue by iamfariba** [surveyjs/widgets#118]
Hi,
i have sortablelist like this in my question, i do not want user drag more than one, how can i put this limitation on it? or is there any other type of question that let user to drag only one thing?
{
            "type": "sortablelist",
            "name": "important-functionality",
            "title": "What is the most important functionality for you?",
            "isRequired": false,
            "colCount": 0,
            "choices": ["A", "B", "C"]
          }
Thank you

**Comment by tsv2013** [comment]
We've implemented the maxAnswersCount feature:
```JS
   {
        "type": "sortablelist",
        "name": "important-functionality",
        "title": "What is the most important functionality for you?",
        "isRequired": false,
        "colCount": 0,
        "maxAnswersCount": 2,
        "choices": ["A", "B", "C"]
      }
```
