### ISSUE TITLE
Display error inside of custom widget

### ISSUE THREAD

**Issue by bogdosarov** [surveyjs/widgets#119]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the expected behavior?
I want to obtain a question error inside of a custom widget and display this error message inside of the widget. Are there any possibilities to do it?

### Specify your

* browser: Chrome
* browser version: latest
* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: latest

**Comment by tsv2013** [comment]
Yes, you can use `question.errors` property and use the
```
/**
   * Register a function that will be called on a property value changed.
   * @param name the property name
   * @param func the function with no parameters that will be called on property changed.
   * @param key an optional parameter. If there is already a registered function for this property witht the same key, it will be overwritten.
   */
  public registerFunctionOnPropertyValueChanged(
    name: string,
    func: any,
    key: string = null
  )
```
function of a question to being notified on property changed

**Comment by bogdosarov** [comment]
@tsv2013  Thank you for the quick answer!

This is fully cower my question. 
```
afterRender: (question, el) => {
      ...
      question.registerFunctionOnPropertyValueChanged('errors', (data) => {
          console.log('registerFunctionOnPropertyValueChanged', data)
      })
     ...
    },
```
