### ISSUE TITLE
widgets doesn't work for nuxt

### ISSUE THREAD

**Issue by lroy83** [surveyjs/widgets#120]
### Are you requesting a feature, reporting a bug or asking a question?

question

### What is the current behavior?

survey is working. widgets are not.

### What is the expected behavior?

I'm trying to set widgets (icheck) for my surveyjs-vue in nuxt.
i managed to install the survey as a plugin, and it works well,
but i can't do the same for the widgets.

it works fine on pure vue app, but not in nuxt.
when debugging, i see the difference in this function:
widgetIsLoaded: function() {
      return typeof $ == "function" && !!$.fn.iCheck;
    }
where iCheck in $.fn in undefined.

did anyone encountered this issue?
 

### Specify your

* browser: chrome
* browser version: 72.0.3626.81
* surveyjs platform (angular or react or jquery or knockout or vue): nuxt
* surveyjs version: 1.0.85

**Comment by tsv2013** [comment]
I've moved this question to the corresponding repo.

**Comment by tsv2013** [comment]
SurveyJS widgets are using 3rd party libraries (integrate them with SurveyJS). The "iCheck" custom widget uses the http://icheck.fronteed.com/ library. Have you loaded all corresponding scripts as shown in this sample https://surveyjs.io/Examples/Library/?id=custom-widget-icheck&platform=Vue&theme=default ?

```
        <script src="https://unpkg.com/icheck@1.0.2"></script>
        <link rel="stylesheet" href="https://unpkg.com/icheck@1.0.2/skins/square/blue.css">
      /// and other used themes CSS files
```

**Comment by lroy83** [comment]
of course i didn't!
and i was afraid it's something stupid....   😁

Thanks man!
