### ISSUE TITLE
Reactjs prettycheckbox checkbox data is not sent in result

### ISSUE THREAD

**Issue by comur** [surveyjs/widgets#122]
Hi,

I have a weird behavior on React with prettycheckbox. Data of checkboxes are not in the result object if I activate the widget. Same as on the exemple on surveyjs docs:
https://surveyjs.io/Examples/Library/?id=custom-widget-pretty-checkbox&platform=Reactjs

Can you give me a workaround or a way to fix it please ? I cannot make work icheck neither and prefer prettycheckbox anyway.

Thanks

**Comment by comur** [comment]
It works in this example (with surveyjs 1.0.64) but not with 1.0.87 as on the docs:
https://plnkr.co/edit/t83Cm57wN6CMv37AdppA?p=preview

**Comment by comur** [comment]
Found breaking surveyjs lib version, it's 1.0.78 and here is the compare:
https://github.com/surveyjs/survey-library/compare/v1.0.77...v1.0.78

I you can help ?

Thx

**Comment by andrewtelnov** [comment]
@comur Yes, I see the issue. We wil take a look.

Thank you,
Andrew

**Comment by comur** [comment]
Thx, I also opened an issue on library's repo (did not see your quick reply) so you can close one of them if needed.

**Comment by andrewtelnov** [comment]
@comur The fix will be included into the minor update on this week.

Thank you,
Andrew
