### ISSUE TITLE
SSN Widget w/ Masking (3rd party widget)

### ISSUE THREAD

**Issue by RA-Work-A** [surveyjs/widgets#124]
[Plunkr ](https://plnkr.co/edit/THp8h1b8t8GiO8muqZ3g?p=info)

What I'm trying to do here, is create a custom widget that takes an ssn w/ formatting while also masking the input. As you can see from the plunkr, the survey will load w/ the custom control, however the ssn.init() function doesn't / won't work. The console.log message I have fires, but the rest of the code won't work unless I call the ssn.init function manually. I'm using the jquery version, so looking at the angular fix from 2018 doesn't help me all that much. 

Is this written correctly? Or is there another issue at work here?

**Comment by tsv2013** [comment]
I've changed your plunker. Please check it - https://plnkr.co/edit/YF4e6Kb3SPUGQp5saMJW?p=preview
