### ISSUE TITLE
Question-sortablelist

### ISSUE THREAD

**Issue by iamfariba** [surveyjs/widgets#125]
Hi,

in surveyjs when i use sortablelist then it gives me two column on top of each other, then i can drage from column to the other column which is on top,

if i want to have these two column next to each other, how can i have it?

i need to have thoseto columns next to each other then i drag items from left column to the right side column,

Best Regards

**Comment by tsv2013** [comment]
I hope styled solution will work for you - https://plnkr.co/edit/HrRvIs6utNJhUcBGalsf?p=preview

I've used the following CSS:

.sjs-sortablejs-root {
  width: 100%;
}
.sjs-sortablejs-root > div {
  vertical-align: top;
  display: inline-block;
  width: 48% !important;
}
.sjs-sortablejs-root > div:last-child {
  margin-left: 2%;
}

https://surveyjs.answerdesk.io/ticket/details/T2117
