### ISSUE TITLE
Will a surveyjs-widgets.d.ts be added in the future?

### ISSUE THREAD

**Issue by zenithA** [surveyjs/widgets#127]
Will a surveyjs-widgets.d.ts be added in the future? 
If not, what would you suggest to add in the interface of an external module declaration?

**Comment by tsv2013** [comment]
We didn't think about the .d.ts for a while.
What are you expecting to get from the declarations? What exact issues have you faced?

**Comment by tsv2013** [comment]
More over, survey-widgets is a pack of all widgets and each of them has it's own .js file in the widgets folder...

**Comment by zenithA** [comment]
The problem is that for an environment configured with the following:

typescript - v3.2.4
survey-angular: 1.0.98
surveyjs-widgets: 1.0.98
jquery: 3.1.1
jquery-ui: 1.12.1
"noImplicitAny": true in tsConfig.json (I can't allow it to be set to false, but even if it is, the widget is still not loaded)
=> I get a ts compile error: `TS7016 Could not find a declaration file for module surveyjs-widgets` ( this is caused by the fact that the library is missing the d.ts file)

If setting noimplicitAny=false, the compile error disappears, but the datepicker element from surveyjs-widgets is not loaded and the following error is returned:
`JsonIncorrectTypeError: The property type is incorrect in the object. Please take a look at property: 'elements'. The following types are available: 'matrixdropdownbase', 'matrixdropdown', 'matrixdynamic', 'matrix', ...", etc`

I have also tried creating a surveyjs-widgets.d.ts file where to declare the module, where I have included the following:
declare module 'surveyjs-widgets' {
    export function jqueryuidatepicker(survey: any): any;
}
But also, even if the ts compile error disappears, the datepicker is not loaded and the error `JsonIncorrectTypeError` is still shown

**Comment by tsv2013** [comment]
@zenithA Are you using the Angular platfotm? We have a sample repo - https://github.com/surveyjs/surveyjs_angular_cli
It demonstrates how to use SurveyJS libraries in an Angular project. Have you seen it?

**Comment by tsv2013** [comment]
See also https://github.com/surveyjs/widgets/issues/121
