### ISSUE TITLE
Error on startup: TypeError: Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by mauringhio** [surveyjs/widgets#133]
Error on application startup:
TypeError: Cannot read property 'fn' of undefined

In my config I'm using:
    "knockout": "^3.4.2",
    "survey-angular": "^1.1.2",
    "surveyjs-widgets": "^1.1.2",

I know that knockout is not the latest, but the downgrade is necessary otherwise the app doesn't compile, I'm using angular 4.4.7, I know it's old but I cannot upgrade at the moment

**Comment by tsv2013** [comment]
Some widgets are using jQuery. Probably jQuery is not loaded.

**Comment by mauringhio** [comment]
It came with the upgrade, with 
"survey-angular": "^1.1.0",
"surveyjs-widgets": "^1.1.0",
it does not occur

**Comment by tsv2013** [comment]
@mauringhio  Can you provide us with a sample to reproduce on our side?

**Comment by tsv2013** [comment]
@mauringhio Sorry for the late response, we were busy with other requests. Please feel free to ping us here if it's crucial issue for you.
