### ISSUE TITLE
Checkbox doesn't' work properly. "splice" is wrong function.

### ISSUE THREAD

**Issue by sergeyPodolskiy** [surveyjs/widgets#134]
When I tried to use checkbox, it doesn't' work properly.
In the File surveyjs-widgets.js has code like 
          var index = oldValue.indexOf(event.target.value);
          if (index >= 0) {
            oldValue.splice(index, 1);
            question.value = oldValue;
          }

Unfortunately, function "splice" called from survey.react.js instead of array.splice.

i Rewrote code (after that works fine):
        if (question.getType() === "checkbox") {
          var oldValue = [];
          question.value.map(function(item) {oldValue.push(item)});
          
          
          // var oldValue = question.value || [];
          var index = oldValue.indexOf(event.target.value);
          if (index >= 0) {
            oldValue.splice(index, 1);
            question.value = oldValue;
          }
        }

**Comment by tsv2013** [comment]
Could you please clarify - what's wrong with the current behavior?

**Comment by sergeyPodolskiy** [comment]
Event does not work when i do uncheck and i need click 3 times instead of 2
that check and uncheck checkbox.

чт, 8 авг. 2019 г., 15:14 tsv2013 <notifications@github.com>:

**Comment by sergeyPodolskiy** [comment]
Event onValueChanged

чт, 8 авг. 2019 г., 15:21 Сергей Подольский <ygypochta@gmail.com>:

**Comment by gologames** [comment]
Hello Sergey,

Indeed this is a bug. We fixed it via [this commit](https://github.com/surveyjs/widgets/commit/381da44e007e48a153e48528200a4c3aef35856d). It will available in package with next minor update

Thanks, Alex
SurveyJS Team

**Comment by sergeyPodolskiy** [comment]
Thanks😀
