### ISSUE TITLE
SortableList inherits irrelevant properties

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/widgets#137]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
It seems the SortableList question type inherits from multiple checkbox; it has some options that seem irrelevant:
- hasNone
- renderAs

# Implementation notes
In sortable list some properties are hidden: https://github.com/surveyjs/widgets/blob/master/src/sortablejs.js#L21
But in Select2 properties are removed:
https://github.com/surveyjs/widgets/blob/master/src/select2.js#L25
 
What is the correct method?

**Comment by tsv2013** [comment]
I've hide these properties
