### ISSUE TITLE
SortableList randomized order not working

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/widgets#138]
Randomizing order of answer options on a SortableList question has no effect.

This JSON was created here: https://surveyjs.io/Examples/Survey-Creator/?id=customwidgets&theme=bootstrap

```json
{
 "pages": [
  {
   "name": "page1",
   "elements": [
    {
     "type": "sortablelist",
     "name": "question1",
     "choices": [
      "Item 1",
      "Item 2",
      "Item 3"
     ],
     "choicesOrder": "random"
    }
   ]
  }
 ]
}
```

**Comment by gologames** [comment]
Hello,

Indeed this is a bug. We are fixed it via [this commit](https://github.com/surveyjs/widgets/commit/014ddc80aaac3ed7a3114e705581c52027ab8182). It will available with next minor update

Thanks, Alex
SurveyJS Team
