### ISSUE TITLE
How to extends default CSS class to the custom Widget?

### ISSUE THREAD

**Issue by virajsonagra** [surveyjs/widgets#144]
Hi,
I am creating my own custom widget using the "radiogroup" class but I am facing an issue regarding the default CSS because my new widget does not have those default CSS classes.

`Survey.JsonObject.metaData.addClass("customradio", [], null, "radiogroup")`

Now, there is a new "Customradio" widget created but it's not getting the default radiogroup classes. I have searched and found that we can use " model.css = css;" and apply those classes at the run time. But I want a solution that how can we set those classes while creating a widget? In widget creating code.

**Comment by tsv2013** [comment]
Here is the custom widget live sample - https://plnkr.co/edit/HdnYE5?p=preview

You can use the following option:
```JS
  //If you want to use the default question rendering then set this property to true. We do not need any default rendering, we will use our our htmlTemplate
  isDefaultRender: false,
```

**Comment by virajsonagra** [comment]
I do not want to create my own HTML structure. I just want all the default CSS class to be available through the widget. For example to my above code. 

` var css = {  "customradio": { "root": "sv_qcbc form-inline",
                        "item": "radio",
                        "itemChecked": "checked",
                        "itemInline": "sv_q_radiogroup",
                        "label": "",
                        "itemControl": "",
                        "itemDecorator": "sv-hidden",
                        "controlLabel": "",
                        "materialDecorator": "circle",
                        "other": "sv_q_radiogroup_other form-control",
                        "clearButton": "sv_q_radiogroup_clear button",
                        "column": "sv_q_select_column"}}
 var model = new Survey.Model({surveyId: surveyId, surveyPostId: surveyId});
                model.css = css;
`
I want to achieve the above result through widget only.

**Comment by tsv2013** [comment]
Sorry, but afraid I don't understand your scenario. Please share a minimal working sample illustrating your question.
