### ISSUE TITLE
Easyautocomplete not working on MatrixDynamic questions

### ISSUE THREAD

**Issue by WJ89** [surveyjs/widgets#145]
The easy-autocomplete widget does not seem to function on an column in a matrixdynamic question,
it is binding to the input but autocomplete is set to off and doesn't function.

Plunker example:
https://plnkr.co/edit/nzFgC31eN8kxEmYVLJFe?p=preview

**Comment by gologames** [comment]
Hello,

We fixed it via commit above. It will available with next minor update. Right now as a workaround you may add code below at the very top of your js file
```javascript
Array.prototype.push.apply(
        Survey.matrixDropdownColumnTypes.text.properties,
        ["choices", "choicesOrder", "choicesByUrl", "otherText"]);
```

**Comment by WJ89** [comment]
Thanks for your quick reply and fix.
This seems to work fine with choicesByUrl on older versions of the library (tested on 1.0.95) but on the newer versions (Tested on 1.1.16 and 1.1.8) it is throwing a Uncaught RangeError: "Maximum call stack size exceeded."

Plunker example (works fine if you downgrade survey.react.js version to 1.0.95):
https://plnkr.co/edit/nzFgC31eN8kxEmYVLJFe?p=preview
