### ISSUE TITLE
nouislider "orientation" flag

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/widgets#155]
need to add this flag to the widget's config https://refreshless.com/nouislider/slider-options/#section-orientation

**Comment by michaelSchrempp** [comment]
Thank's for creating the issue!
Regarding the feature:
All you have to do is to add "orientation: question.orientation" where the noUislider is created (noUiSlider.create(el, ... )).
Furthermore as is it says in the docs: "Set dimensions!". I would set a fixed height of 250px, when the orientation is set to vertical.

**Comment by dmitrykurmanov** [comment]
@michaelSchrempp greate! I've tested and merged your pull request. Feature will be available in the next minor release.

**Comment by dmitrykurmanov** [comment]
@michaelSchrempp please feel free to add any notes and I'll reopren the issue in this case.

**Comment by michaelSchrempp** [comment]
@dmitrykurmanov Thank you very much for testing my PR this quickly! :)
- Reopening is not necessary
