### ISSUE TITLE
Custom widget for vuejs-datepicker

### ISSUE THREAD

**Issue by CaptainCannabis** [surveyjs/widgets#162]
* Vue: v2.6.11 
* surveyJS (Vue): v1.1.31
* Vuejs-datepicker: v1.6.2

I am trying to use [vuejs-datepicker](https://github.com/charliekassel/vuejs-datepicker) as a custom widget in surveyJS for enhancing the standard-date-input. I know there are solutions with jQuery and so on, but i am wondering if it is possible to get this up and running in the surveyJS-Vue-version.

You can look up the setup [here](https://next.plnkr.co/edit/oELKGeqAKy6d1ezS).

### What is the expected behavior?

Definitely an issue. I am wondering what exactly ist happening behind the scenes when i register the widget by using `Survey.CustomWidgetCollection.Instance.addCustomWidget(widget,"customtype");` (see line 43 in surveyConf.js .

If i comment these out i get a normal text input element. If i pass the widget and create the survey with it loaded i get an input with the datepicker but it seems that the property "htmlTemplate" has no or not the expected effect. With an empty string i get an datepicker input in the element which is logged in line 28 as "element root". If i fill in for example `<div>Test</div>` these html is rendered but the datepicker magically appears too below.

So it seems as the widget always creates an `<datepicker/>`-tag which is rendered as the datepicker with default settings. My expectation was that i can pass some props along with the datepicker-tag like `<datepicker :inline="true"></datepicker>`

So i am wondering how to use a vue-component in a custom-widget and pass props to it. Another thing i did not understand till now is that the "isFit"-method only works with the current condition by checking for type "text" and inputtype "date". If i try to use line 17 (commented out right now) and set these value as element-type "isFit" won't resolve to true. But i saw it working in some jQuery based examples.

**Comment by tsv2013** [comment]
There is no framework-specific context Inside the `afterRender` function of a custom widget. That's why your `datepicker` tag still the `datepicker` tag.

The survey-widgets is a framework-agnostic package. According our custom widgets vision every custom widget should work within all the frameworks (platforms) - jQuery, VueJS, ReactJS and so on.
That's why custom widgets are written in pure JS (sometimes jQuery) with dependencies to the certain 3rd party libraries.

Probably you can declare your custom question type and register it in a manner of other our question types, e.g. https://github.com/surveyjs/survey-library/blob/master/src/vue/boolean.vue
But to be honest I've never tested it before. It should work but I'm not sure it will be easy for the first time.

**Comment by CaptainCannabis** [comment]
Thanks for your quick reply. I understand the aproach surveyJS has choosen here. But thought that the widget will only insert the html-content and then execute whatever is inserted, so that an inserted vue-tag which Vue knows about (because loaded before) would be excecuted as if it would be parsed out of surveyJS in the "app"-div.

To this point i don't understand why or where surveyJS is inserting the default-component-settings and template. If i pass it in the widget-property "htmlTemplate" it is not picked up by vue.

So i guess there are two possible solutions:

* Using a widget and setting the datepicker-props after creation by using the event-methods of surveyJS. Dont know if these will work with vuejs-datepicker and how it would affect the rendering.

* Implementing it as a new questiontype as u suggested. I will look into this.

**Comment by tsv2013** [comment]
The "afterRender" method of a widget is called (and widget "htmlTemplate" applied) after VueJS applied it bindings and generated markup. This markup is invisible for VueJS, out of it binding context. That's why it isn't being applied.

**Comment by CaptainCannabis** [comment]
> The "afterRender" method of a widget is called (and widget "htmlTemplate" applied) after VueJS applied it bindings and generated markup. This markup is invisible for VueJS, out of it binding context. That's why it isn't being applied.

Got that, but why is the content of "htmlTemplate" ignored by vue if it is a tag which represents a component which is already registeres in Vue?

The fact that i see a default-datepicker means to me that the whole widget-config is ignored and 
 line 43 in surveyConf.js `Survey.CustomWidgetCollection.Instance.addCustomWidget(widget,"customtype");`
which loads the component, simply calls the default constructor. 

I got that right?

**Comment by CaptainCannabis** [comment]
> But to be honest I've never tested it before. It should work but I'm not sure it will be easy for the first time.

I would like to use embedded vue-components inside the htmlTemplate as mentioned before. For now i am using "tiny date picker" which comes with an "permanent"-mode. This fits my needs and seems to work

https://run.plnkr.co/plunks/U68Attz7mBvxnrl5/
