### ISSUE TITLE
Select2 not updating on change locale ( React, Vue )

### ISSUE THREAD

**Issue by xxxKOTxxx** [surveyjs/widgets#186]
Hi!

I'm trying to implement multilanguage survey on React, but have some trouble with Select2 and localization.

I created [example](https://plnkr.co/edit/H4FvWkD2cFl2Tq9H) to reproduce issue.

So, when I toggle language, standart select is updaing localized strings as expected, but rendered as select2 is not changing. What am I doing wrong?

Same with tagbox widget

P.S.
If You uncomment string 88 (// var mode = 'display') and toggle locale You'll get console errors like
`Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor).`

**Comment by tsv2013** [comment]
This is a bug of the select2 custom widget (most likely not implemented functionality). We'll work on it.

**Comment by xxxKOTxxx** [comment]
> This is a bug of the select2 custom widget (most likely not implemented functionality). We'll work on it.

Can You add workaround using `onPropertyChange` callback with chek `name === 'locale'` and updateChouses call for now as temporary solution f.e.?

**Comment by dmitrykurmanov** [comment]
We've fixed the problem. Fix will be available in the next minor release.
