### ISSUE TITLE
Problem with dropdown display mode rendering

### ISSUE THREAD

**Issue by xxxKOTxxx** [surveyjs/widgets#187]
Hi!

I don't know what do You have against `disabled` attribute (it supported by both: HTML `SELECT` element and select2 options), but dropdown in both rendering modes (renderAs) in display mode rendered as `DIV` with attribute `disabled` (AFAIK `DIV` not supportting `disabled`).

So the problem is that You rerendering template (`SELECT`  <=> `DIV`) without firing `onAfterRenderQuestion` callback. Side effect of this behaviour is removing modifications added in `onAfterRenderQuestion` callback. How can I workaround this?

To understand what I mean, please, check [example](https://plnkr.co/edit/Nf2dQ2e8yY1vj5pw): Custom label is disappearing in display mode and never come back without page reload.

**Comment by tsv2013** [comment]
This is a bug of the select2 custom widget (most likely not implemented functionality). We'll work on it.

**Comment by xxxKOTxxx** [comment]
This bug reproducing with `renderAs = 'standart'` - so it's not only a select2 problem.

**Comment by andrewtelnov** [comment]
@xxxKOTxxx I have fixed the issue by the commit above.

Thank you,
Andrew
