### ISSUE TITLE
select2 widget not working with choicesByUrl

### ISSUE THREAD

**Issue by cinziasala** [surveyjs/widgets#19]
I wonder if it is possible to use choicesByUrl on values different from name.
In this example I would like to select among capitals
    {
      "type": "dropdown",
      "renderAs": "select2",
      "choicesByUrl": {
        "url": "https://restcountries.eu/rest/v1/all",
        "valueName": "capital"
      }

https://plnkr.co/edit/TRPKgM4Qz08tivp5tLeF?p=preview

I am a newbie and not a developer and I have not found any solution yet. Your help will be crucial for me.
Thanks

**Comment by andrewtelnov** [comment]
@cinziasala I could not reproduce the problem. It works as expected. You may need to wait for some times on the first request. I guess the issue, that nobody wa using the service for a while and it was needed to start-up.

Thank you,
Andrew

**Comment by cinziasala** [comment]
Thanks @andrewtelnov 

Capitals are correctly loaded, but when I try to filter a capital (i.e. Rome) dose not get the data.

![screen shot 2018-01-15 at 10 32 11](https://user-images.githubusercontent.com/4437896/34935852-8a12edc6-f9df-11e7-83fc-110cbda3804f.png)

**Comment by andrewtelnov** [comment]
@cinziasala It is likely a bug of select2, "Uncaught TypeError: Cannot read property 'replace' of null" - it generates by select2 when you are starting to type in the filter.
I have tried to google it, but I do not know how to avoid it yet.

Thank you,
Andrew

**Comment by masciugo** [comment]
it actually works with some fields. In this plunker the dropdown returns `alpha2Code` as valueName https://plnkr.co/edit/MIlqCVVhQcNJoWMhz1dJ?p=preview 

But it does not work if field capital or region (and most likely some others) are returned

**Comment by tsv2013** [comment]
Here is the live sample uses the `choicesByUrl` option - https://surveyjs.io/Examples/Library/?id=custom-widget-select2&platform=jQuery&theme=default
