### ISSUE TITLE
NoUISlider: Format Data as Number

### ISSUE THREAD

**Issue by johannesschobel** [surveyjs/widgets#193]
Dear @andrewtelnov and @dmitrykurmanov ,

in #165 we discussed, if the **display value** in the tooltip could be manipulated in order to not show decimal points. However, in this context, i noticed, that the actual value returned by the `NoUiSlider` is a string `"12.34"` and **not** a `Number`.

I think, it would be better to actually cast the return value to a `Number`, like so:
```ts
slider.on("change", function() {
  question.value = Number(slider.get());
});
```
in this file https://github.com/surveyjs/widgets/blob/master/src/nouislider.js#L103-L105

Beside the type cast, this will not be a breaking change. What do you think?
All the best

**Comment by tsv2013** [comment]
I think we can add this change. Could you please create a PR?

**Comment by johannesschobel** [comment]
sure.. will do this tomorrow.. 
Thanks a lot!

**Comment by johannesschobel** [comment]
Dear @tsv2013 , please check out #195 
All the best
