### ISSUE TITLE
sortable list text changing not working on typing or on blur

### ISSUE THREAD

**Issue by WoodenPC** [surveyjs/widgets#204]
### Are you requesting a feature, reporting a bug or ask a question?

bug

### What is the current behavior?

text changing after adding or removing item in sortable list

### What is the expected behavior?

text changing on typing or on blur

### How would you reproduce the current behavior (if this is a bug)?

https://surveyjs.io/Examples/Builder/?id=customwidgets
select sortable list widget, open choices property, change text in any item -> text is not updating on view

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://surveyjs.io/Examples/Builder/?id=customwidgets

### Specify your

* browser: google chrome/ firefox
* editor version: last version

**Comment by andrewtelnov** [comment]
@WoodenPC I have fixed the issue. We will include fix in v1.7.21 that we are going to release today/tomorrow.

Thank you,
Andrew

**Comment by WoodenPC** [comment]
Thank you very much! @andrewtelnov please look at the other props too, it seems that update of "empty text" prop also not working. Idk, maybe this problem can be related to other props in sortablelist widget?
![image](https://user-images.githubusercontent.com/25397745/88193043-e2e9bc00-cc45-11ea-83ab-1f00bf8d68cf.png)

**Comment by andrewtelnov** [comment]
@WoodenPC I have fixed it as well and move properties into "general" tab.

Thank you,
Andrew

**Comment by WoodenPC** [comment]
@andrewtelnov Are u sure "empty text" is fixed ? I checked it again and seems it still broken

**Comment by andrewtelnov** [comment]
@WoodenPC It is fixed in v1.7.24 that we are not released yet. You did not create a new issue, that is why there is a misunderstanding. Here is [the commit](https://github.com/surveyjs/widgets/commit/1398ce43ea8a8cb743d1efd57cd9846b83f29e36).

Thank you,
Andrew
