### ISSUE TITLE
IE11 "multiple definitions strict mode" bug

### ISSUE THREAD

**Issue by xxxKOTxxx** [surveyjs/widgets#212]
I got IE11 error "multiple definitions strict mode".

Inspection show that it caused by next code:

`e.JsonObject.metaData.addProperty("sortablelist",{name:"emptyText",category:"general",default:"Move items here.",category:"general"})`

I think problem is in duplicated `category` property. I found at least 3 duplications.

Can You fix it?

**Comment by tsv2013** [comment]
How can we reproduce the issue?

**Comment by xxxKOTxxx** [comment]
> How can we reproduce the issue?

In my case it's `react` app with '"use strict";' and `IE 11.0.9600.18860`

In repo `src/sortablejs.js` we can find on line 35 next code:
`
      Survey.JsonObject.metaData.addProperty("sortablelist", {
        name: "emptyText",
        category: "general",
        default: "Move items here.",
        category: "general",
      });
      Survey.JsonObject.metaData.addProperty("sortablelist", {
        name: "useDefaultTheme:switch",
        category: "general",
        default: true,
        category: "general",
      });
      Survey.JsonObject.metaData.addProperty("sortablelist", {
        name: "maxAnswersCount:number",
        category: "general",
        default: -1,
        category: "general",
      });
`

In any case: what sense in `category: "general",` duplication? It's an issue I think.

**Comment by tsv2013** [comment]
Thanks, I see now. I should be more scrupulous. It's a bug indeed. We'll fix it.

**Comment by tsv2013** [comment]
Fix will be available in 1.8.2
