### ISSUE TITLE
cascade dropdown not working with select2

### ISSUE THREAD

**Issue by masciugo** [surveyjs/widgets#24]
simple working dropdown version:
https://plnkr.co/edit/RzlaGCgqgbBRO0oUP6sn?p=preview

select2 not working version:
https://plnkr.co/edit/cwMrBPcpc5ZTPUjYbtnD?p=preview

.. or to be precise It updates the 2nd dropdown only when you change the 1st dropdown for the first time

**Comment by dmitrykurmanov** [comment]
Thank you for feedback, we've fixed the bug, fix will available in the next patch release
