### ISSUE TITLE
InputMask Phone Bug in Angular2

### ISSUE THREAD

**Issue by wollerman** [surveyjs/widgets#25]
Trying out the InputMask with json of:
```
    {
     "type": "text",
     "inputMask": "phone",
     "name": "phone"
    }
```

does not render correctly. It displays the text `phone` in the field and doesn't allow for any number entries. Below is a screenshot of what I see with a clone of https://github.com/surveyjs/surveyjs_angular_cli
![image](https://user-images.githubusercontent.com/1610241/35164690-4594911c-fd00-11e7-9119-bb76aa29d655.png)

**Comment by tsv2013** [comment]
Thank you for the report. I've reproduce the issue. We'll fix it.
