### ISSUE TITLE
Bar Rating Bug in Angular2

### ISSUE THREAD

**Issue by wollerman** [surveyjs/widgets#26]
Using the [surveyjs_angular_cli project the `barrating` type should be available](https://github.com/surveyjs/surveyjs_angular_cli/blob/master/src/app/survey.component.ts). However, when trying to use this in the json editor, it provides the message:
```
Error: The property type is incorrect in the object. Please take a look at property: 'elements'. 
The following types are available: 
'checkbox', 'radiogroup', 'dropdown', 'matrixdropdownbase', 
'matrixdropdown', 'matrixdynamic', 'matrix', 'text', 'multipletext', 
'empty', 'comment', 'file', 'rating', 'expression', 'boolean', 'paneldynamic'.
```

Inspecting `Survey.JsonObject.metaData.classes` also shows that `barrating` is not showing up.

**Comment by tsv2013** [comment]
We've fixed the issue. Fix will be available in v1.0.4.
