### ISSUE TITLE
Request datetimepicker widget

### ISSUE THREAD

**Issue by ShadowFoOrm** [surveyjs/widgets#27]
Hi guys,
I love surveyjs and I know there is a datepicker widget but can we have a datetimepicker as well ?
The datepicker can't pick the time at the moment.

![image](https://user-images.githubusercontent.com/13979327/35274242-47f3ee86-0033-11e8-8d4c-bb12d14346b1.png)

jquery-datetimepicker or bootstrap datetimepicker or anything better ?

**Comment by tsv2013** [comment]
Thank you for the request. We've added it to our TODO list. Right now I can't give you any estimations.

**Comment by tsv2013** [comment]
Nobody asked for the datetimepicker widget since Jan, 2018
Closing for a while
