### ISSUE TITLE
Reverse input and label positioning for pretty-checkbox widget?

### ISSUE THREAD

**Issue by jbdivups** [surveyjs/widgets#29]
Trying to have label on left and radio input on right. Any help is much appreciated. Thanks for the great library.

**Comment by tsv2013** [comment]
You can just add css from this answer (https://github.com/lokesh-coder/pretty-checkbox/issues/34) to the page with SurveyJS.
I'd also recommend to increase the right padding of the label:
```CSS
  padding-right: 1.5rem;
```
