### ISSUE TITLE
Angular 5 CLI + TypeScript 2.6 example

### ISSUE THREAD

**Issue by halexiev-hedgeserv** [surveyjs/widgets#34]
Hello,

Would it be possible to provide a more recent angular-cli example with surveyjs widgets?

Thank you,
Hristo

**Comment by tsv2013** [comment]
Sure. You can check this repo - https://github.com/surveyjs/surveyjs_angular_cli
I've just updated it up to Angular 5 according tp these instructions (https://github.com/angular/angular-cli#user-content-updating-angular-cli and https://angular-update-guide.firebaseapp.com/)
It works ok for me

**Comment by halexiev-hedgeserv** [comment]
Thank you for the reply!

One issue though - I updated Angular and TS versions to 5.2 and 2.6.2 and it works, but really slow with the json we are using.

Would it be possible to have a look and maybe point us to the reason why when you start the app and just toggle the answers of the first question is takes considerable amount of time to update the dependent questions? 

What's even more baffling is that the more you toggle the answers of the first question the slower it gets...

Just as FYI - we have been using the jquery version of SurveyJS with same json in an Aurelia app so far and have not had this slowness.

[surveyjs_angular_cli-master.zip](https://github.com/surveyjs/widgets/files/1723348/surveyjs_angular_cli-master.zip)

**Comment by tsv2013** [comment]
Closed due to duplicated in the https://github.com/surveyjs/surveyjs/issues/922
