### ISSUE TITLE
'survey' is not defined.

### ISSUE THREAD

**Issue by adius** [surveyjs/widgets#36]
Hi,
I used [Feram] to check your repo and found this issue:

"'survey' is not defined."

```diff
--- index.js
+++ index.js
@@ -50,1 +50,1 @@
   $("#surveyElement").Survey({
-    model: survey // FIXME //
   });  
 }
 

```

I hope it helps!

If you want to use it as well, it’s for free and really simple to integrate:
[feram.io/help/getting-started]

[Feram]: https://feram.io
[feram.io/help/getting-started]: https://feram.io/help/getting-started

**Comment by tsv2013** [comment]
Thanks, this variable was initialized two lines before:
```JS
window.survey = model;
```

**Comment by adius** [comment]
Thanks for the feedback!
Weird that it didn't notice it. I'll look into it..
