### ISSUE TITLE
Prettycheckbox library was not found on the page if used as bundled css

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/widgets#38]

**Comment by tsv2013** [comment]
For more details see https://github.com/surveyjs/widgets/issues/35

@tsv2013 I tried the pretty-checkbox route, but for some reason the "renderAs" property does not apply - is there some special configuration to make it work?

**I tried the following:**
Installed the pretty-checkbox npm package.

Added the following import in the global styles.scss:
`@import '~pretty-checkbox/src/pretty-checkbox.scss';`

Added the following In the surveyjs.component.ts:
```
import * as Survey from 'survey-angular';
import * as widgets from 'surveyjs-widgets/surveyjs-widgets.js'
widgets['prettycheckbox'](Survey);
```

Finally modified one of the questions in the json like this:
```
    {
      "elements": [
        {
          "type": "checkbox",
          "renderAs": "prettycheckbox",
          "name": "SidePocketElection",
          "title": "Election Not to Participate in Illiquid Sub-Capital Accounts. Check the box below if the Subscriber elects not to participate in Illiquid Sub-Capital Accounts, as described in Section 5.5(b)(i)(C) of the Agreement and in the Offering Circular. By checking this box, the Subscriber acknowledges that it will not be entitled to participate in the Master Fund’s investments in Illiquid Instruments.",
          "isRequired": true,
          "choices": [
            {
              "value": "SPLiq_1",
              "text": "Election Not to Participate in Illiquid Sub-Capital Accounts."
            }
          ]
        }
      ],
      "name": "SidePocketElectionSection",
      "title": "SidePocket Election",
      "visible": false,
      "visibleIf": "{InvestorType}='individual' or {InvestorType}='entity'"
    }

```

Is this a bug - any suggestions?

Thank you,
Hristo

**Comment by tsv2013** [comment]
We've fixed "pretty-checkbox library was not found for bundled CSS" issue and updated the https://github.com/surveyjs/surveyjs_angular_cli repo (commit surveyjs/surveyjs_angular_cli@c671bf1)
Fix will be available in the next update

**Comment by halexiev-hedgeserv** [comment]
@tsv2013 Thank you! I applied the changes from your commit locally and widget is loading now 👍
