### ISSUE TITLE
Pull request - add boolean question type support in pretty-checkbox widget.

### ISSUE THREAD

**Issue by halexiev-hedgeserv** [surveyjs/widgets#39]
Hi guys,

Pretty checkbox widget does not support 'boolean' type of questions for some reason, so I gave it a try to implement it and therefore the patch (pull request) attached below as I don't have permissions to create a branch.

Added as well is support for the various pretty checkbox states based on the css classes in widget.settings.

Please let me know if any issues - we are betting on surveyjs & widgets so we'd love to help.

[add_boolean_question_type_support.patch.zip](https://github.com/surveyjs/widgets/files/1740109/add_boolean_question_type_support.patch.zip)

**Comment by tsv2013** [comment]
@halexiev-hedgeserv Thank you for your efforts! We'll check your patch.

One little note - it is better to use github pull request tools instead of archieve exchange ;-)

**Comment by halexiev-hedgeserv** [comment]
@tsv2013 Thank you, pull request created:

https://github.com/surveyjs/widgets/pull/40
