### ISSUE TITLE
Add my own custom widget

### ISSUE THREAD

**Issue by guilhermesad** [surveyjs/widgets#44]
Hi! I would like to use [Ziggeo](https://ziggeo.com/) as a widget for video recording. How can I create my own widget and add it to the SurveyJS Builder without having to wait for it to be added to this list: https://github.com/surveyjs/widgets#widgets--

**Comment by andrewtelnov** [comment]
@guilhermesad We do not have a tutorial yet. We will work on it.
You may find [this issue](https://github.com/surveyjs/surveyjs/issues/998) useful
You may look at [microphone widget](https://github.com/surveyjs/widgets/blob/master/src/microphone.js) it was created by @baminmru. 

Thank you,
Andrew

**Comment by guilhermesad** [comment]
Hi @andrewtelnov, thanks for the reply. I had seen these links but I'm actually looking for how to use it in the survey builder. The [example](https://surveyjs.io/Examples/Builder/?id=customwidgets) on this doesn't seem to show how exactly I can do this integration.

**Comment by andrewtelnov** [comment]
@guilhermesad It is pretty much the same. Here is [the example](https://surveyjs.io/Examples/Builder/?id=customwidgets)

Thank you,
Andrew

**Comment by dmitrykurmanov** [comment]
Hello "Edit in Plunker" for this example doesn't work. Because of missed jquery dependency. I've fixed it via adding jquery.  Please see https://plnkr.co/edit/XAOhyVxq5KkBYjOLKVO2?p=preview

And may be you are looking for this code (get from [microphone ](https://github.com/surveyjs/widgets/blob/master/src/microphone.js) implementation)
```
    activatedByChanged: function(activatedBy) {
      Survey.JsonObject.metaData.addClass("microphone", [], null, "empty");
    },
```

PS the example fix will be available on the site in the next patch relese.

**Comment by guilhermesad** [comment]
What I'm trying to do is actually quite simple. I have your [nodejs repo](https://github.com/surveyjs/surveyjs-nodejs) running and I want to add a new custom option to the editor.

If I for example copy and paste your [microphone](https://github.com/surveyjs/widgets/blob/master/src/microphone.js) widget into the [editor file](https://github.com/surveyjs/surveyjs-nodejs/blob/master/public/editor.js) the microphone option doesn't show up in the editor.

**Comment by dmitrykurmanov** [comment]
I've modify my example: https://plnkr.co/edit/XAOhyVxq5KkBYjOLKVO2?p=preview . Now we have one custom widget file which just add as script without any special code and the editor see it.

**Comment by guilhermesad** [comment]
Thanks! That's useful. I've managed to create my own widget following that example. I appreciate your help.

**Comment by dmitrykurmanov** [comment]
@andrewtelnov , @tsv2013  may be we need to create a simple tutorial with an example in the README and our site.

**Comment by JaneCoder** [comment]
Hello!

Is there a way to use the "creator.**toolbox.addItem**(someJson)" function to connect a custom widget to the form creator? 

Or is there some other glue between the survey and the creator?

I'm using your node modules in a ruby app using webpacker. Our package.json pulls in:

    "survey-jquery": "^1.0.91",
    "survey-creator": "^1.0.91",

Do I need something else? Thanks for any advice.

**Comment by andrewtelnov** [comment]
@JaneCoder 
1) Please review the document about [Survey Creator integration](https://surveyjs.io/Documentation/Survey-Creator/?id=Add-Survey-Creator-into-your-Web-Page). You do not need jquery version here. You need a knockout SurveyJS library version and knockout.
2) If you need to add custom widgets from our library, then please review [this example](https://surveyjs.io/Examples/Survey-Creator/?id=customwidgets)
3) If you need to add your own custom widget then this [one](https://next.plnkr.co/edit/fXsLf1R88WxxDFaFEnYx?p=preview&preview).

Thank you,
Andrew

**Comment by JaneCoder** [comment]
Thank you so much!

Is it possible to do it with node modules required in a package.json rather
than script tags as the examples show?

**Comment by kipkiruitoo** [comment]
Just adding the files doesn't add the custom widgets to the survey creator

**Comment by kipkiruitoo** [comment]
Do the custom widgets need to be registered to the Survey Creator?

**Comment by tsv2013** [comment]
@kipkiruitoo Custom widgets are registered automatically in SurveyJS Creator after init call.
If you are using SurveyJS Creator with non-knockout platform, e.g. survey-angular, you need to register a custom widget in survey-knockout platform to be visible in SurveyJS Creator, see the https://github.com/surveyjs/surveyjs_angular_cli/blob/master/src/app/survey.creator.component.ts#L8-L20 sample

**Comment by kipkiruitoo** [comment]
@tsv2013 Thank you, how is the same done in JQuery version of the creator
