### ISSUE TITLE
Display mode causes imagepicker to not show up at all

### ISSUE THREAD

**Issue by denvaar** [surveyjs/widgets#45]
I spent a long time trying to figure out why the image-picker would not render, and finally found that it was the display mode causing it to not show up. If I set `model.mode = 'display'` then the image picker does not show up.

I would expect the widget to still show the pictures ([like in [this plunker](https://plnkr.co/edit/?p=preview),) but maybe not be selectable.

What would it take to make this change?

**Comment by tsv2013** [comment]
I've added corresponding code. Fix will be available in the nearest update.
