### ISSUE TITLE
allowClear option on select2 dropdown

### ISSUE THREAD

**Issue by masciugo** [surveyjs/widgets#52]
I tried to add the option _allowClear_ to the select2 settings but the "x" button doesn't appear

https://plnkr.co/edit/sVoudSOPCdVyfRjM3Fte?p=preview

**Comment by dmitrykurmanov** [comment]
@masciugo by the way, about `select2Config` name, we think that just `config` will be much better. What do you think? Or may be `widgetConfig` ?

**Comment by masciugo** [comment]
mmm that's not obvious. Fact is that often but not always there is a third party library that could be set up with its own options like select2. I think its clearer referring to this particular settings directly specifying its name someway but, in general, a widget may have additionally its own settings. Maybe it's too complicated but I would propose something like:
```js
config: {
  select2: {
    allowClear: true
    // ... other select2 lib settings ....
  },
  // otherThirdPartyLib {
  // },
  // widgetSetting1: ...,
  // widgetSetting2: ...
}
```

**Comment by dmitrykurmanov** [comment]
I think that we use only one widget per question one time. So we have the context. If we are using select2 then `config` associated with this library. But if we use widget by type we don't have any clear context... may be  `select2Config` is good compromise

**Comment by dmitrykurmanov** [comment]
Fix will be wavilable in the next minor. Here an example https://plnkr.co/edit/r8zspi?p=preview @masciugo could you check it please?

**Comment by masciugo** [comment]
I meant more than one third party libs per widget. But even in this case your solution (_ select2Config_) still works because you just need to add _anotherLibConfig_ if necessary. Other widget settings my be passed as question properties in case of widget activated by type

**Comment by masciugo** [comment]
it seems ok but when used with select2 _tags_ option and create a new option you need to click twice to clear

**Comment by dmitrykurmanov** [comment]
@masciugo  yes, becasue of `tags` we've created select2-tagbox widget. It based on checkbox instead of dropdown.

**Comment by masciugo** [comment]
@dmitrykurmanov [select2 tags option is for option creation ](https://select2.org/tagging) while select2-tagbox widget is for multiple select. I need to create to create an option in a select2 powered dropdown. To solve the twice-click problem I needed to add

```
$el.on("select2:unselecting", function (e) {
  question.value = null;
});
```
in the _afterRender_ widget function
