### ISSUE TITLE
Removing custom widgets from toolbox

### ISSUE THREAD

**Issue by mkgn** [surveyjs/widgets#53]
I have disabled some default toolbox items from surveyjs editor. However I still see noUISlider, Signaturepad, sortable list, bootstrap slider.

How can I remove them from the editor?

**Comment by andrewtelnov** [comment]
@mkgn Does this example work for you?
http://localhost:62946/Examples/Builder/?id=toolboxcustomization#content-docs
You may always remove  scripts for noUISlider, Signaturepad, sortable list, bootstrap slider from your page. As result they will be disappeared from the Toolbox as well.

Thank you,
Andrew

**Comment by mkgn** [comment]
I see.. but may be it's better to have a configurable option similar to what you have to disable standard controls. May be pass the unique Name of the widgets to disable them?

Anyway for the moment this would do. Thanks!

**Comment by mkgn** [comment]
I see.. but may be it's better to have a configurable option similar to what you have to disable standard controls. May be pass the unique Name of the widgets to disable them?

Anyway for the moment this would do. Thanks!
