### ISSUE TITLE
signature_pad resizable canvas example

### ISSUE THREAD

**Issue by wollerman** [surveyjs/widgets#55]
Is it possible to get an example of the signature pad resizing? 

Based on https://github.com/surveyjs/widgets/blob/master/src/signature_pad.js#L62-L65 

it seems like this should be possible. But I can't seem to see the question width change from the [default 300](https://github.com/surveyjs/widgets/blob/master/src/signature_pad.js#L46) unless I specify it in the json, and at that point it's still static.

Thanks!

**Comment by tsv2013** [comment]
Now resize it triggered on value changed only - https://github.com/surveyjs/widgets/blob/master/src/signature_pad.js#L62-L69
As a workaround you can change width/height and update question value. This causes canves resizing.

In generel we need to subscribe size and make corresponding updates.

**Comment by wollerman** [comment]
Yes, this is my question. How do I modify the question width/height?

**Comment by tsv2013** [comment]
Sorry if I was unclear.
For a while widget doesn't update canvas size on question width/height properties changes.
I've just implemented it via the https://github.com/surveyjs/widgets/commit/172846875ed2d471be4c8dcfa0ef410e155d6dad commit.
In will be available in the nearest update.

As a temporary workaround you can change width/height, then change value and this sequence will cause canvas resize also.

**Comment by wollerman** [comment]
Awesome! Thanks for the help!
