### ISSUE TITLE
Display mode does not work with tagbox widget

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/widgets#56]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

Tagbox dropdown is selectable when mode === 'display'

### What is the expected behavior?

Tagbox dropdown shoud not be selectable when mode === 'display'

### How would you reproduce the current behavior (if this is a bug)?

https://plnkr.co/edit/ICfNz8AUW9CaMboVRXV5?p=preview

**Comment by tsv2013** [comment]
@wysoki89 An i right? Does your issue https://github.com/surveyjs/surveyjs/issues/1132 releted to this repo?

**Comment by wysoki89** [comment]
thats right

**Comment by tsv2013** [comment]
Fixed. Fix will be available in the nearest update.
