### ISSUE TITLE
enableIf doesn't seem to work correctly on a dropdown element (rendered as a select2 widget)

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/widgets#57]
### How would you reproduce the current behavior (if this is a bug)?

If i try to fill up the text element, the dropdown keeps being disabled.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/oJKHxbgyp4LOuABtOwjz?p=preview

### Specify your

* browser: Google Chrome
* browser version: Latest version
* surveyjs platform (angular or react or jquery or knockout or vue): angular
* surveyjs version: Latest

thanks in advance

**Comment by tsv2013** [comment]
This functionality hasn't been implemented for the custom widgets at all. And we need time to implement it or community suport...
@andrewtelnov @dmitrykurmanov  What do you think?

**Comment by rekotc** [comment]
Oh, i see. The visibleIf property works correctly, i thought the same was for enableIf property...

**Comment by andrewtelnov** [comment]
@tsv2013 Lets add it into our TODO list.

Thank you,
Andrew

**Comment by tsv2013** [comment]
Fixed in 1.0.25
Update released
