### ISSUE TITLE
Widgets for Smiley Rating

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/widgets#58]
moved from https://github.com/surveyjs/surveyjs/issues/1150

**Comment by khaled-ansary** [comment]
Hi, thanks your help. I just checked it and it is working when the `disable` field set as `false`.
https://plnkr.co/edit/DxOg4h?p=preview

**Comment by dmitrykurmanov** [comment]
@khaled-ansary oh great! my mistake, I missed it. Thanks. I've updated the plunk :  https://plnkr.co/edit/eT5Jxm?p=preview Could you check it please?

**Comment by dmitrykurmanov** [comment]
PS I have some problem with plnkr. Here the correct link: http://plnkr.co/edit/NqQw47BQtZhRXZPPrqwu?p=preview

**Comment by khaled-ansary** [comment]
@dmitrykurmanov Its working perfectly for me too. Do you have plan to add it with the next release, then I will just update my current SurveyJS version. Thanks a lot.

**Comment by khaled-ansary** [comment]
I am facing one problem that it always set the last input for the next smiley rating.
For example, if I set 3 smiley rating as a answer and then press the next button for another smiley rating question, it will show by default the previous rating that I selected before.

**Comment by dmitrykurmanov** [comment]
@khaled-ansary fixed, please check http://plnkr.co/edit/NqQw47BQtZhRXZPPrqwu?p=preview

**Comment by khaled-ansary** [comment]
@dmitrykurmanov great. It's working now. Just like to inform about another good library developed using angular http://uttesh.com/ngreactions/ . It has more good feature.  But, I am not sure about the possibility to develop the widget using angular instead of JQuery.

**Comment by dmitrykurmanov** [comment]
Yes it may be hard to integrate it. Thanks for sharing and interest!
