### ISSUE TITLE
noUiSlider ignores survey.data and survey.mode

### ISSUE THREAD

**Issue by pkoziol** [surveyjs/widgets#59]
When I set `data` property, survey is filled with user's answers. Combined with `mode = 'display'` it allows to display already filled surveys as read-only.

It's great, but noUiSlider widget ignores these properties and always starts default value and allows changing value.

I've reproduced it in Plunker: https://plnkr.co/edit/lig8tiqnt5WewhtYML1y?p=preview

**Comment by andrewtelnov** [comment]
@tsv2013 @dmitrykurmanov We have add support for readOnly to all our customWidgets and update the docs

**Comment by andrewtelnov** [comment]
@pkoziol the issue with nouislider is fixed. The fix will be available in the next update.

Thank you,
Andrew
