### ISSUE TITLE
Error in ReactJS v16, Webpack v3.5

### ISSUE THREAD

**Issue by bschellekens** [surveyjs/widgets#60]
Hi there!

I'm integrating the SurveyWidgets in an existing project, build with the latest reactJS starter app and I think I'm running into a webpack dependancy issue. Anyone already running SurveyJS-Widgets under the latest ReactJS?

The error that I'm getting is:
`TypeError: __WEBPACK_IMPORTED_MODULE_0_signature_pad___default.a is not a constructor`

Found in the core node_modules of surveyjs-widgets, node_modules/surveyjs-widgets/surveyjs-widgets.js:989:
` 989 |   var signaturePad = new __WEBPACK_IMPORTED_MODULE_0_signature_pad___default.a(canvas);`

I've compared the package.json with the starter kit and the last ReactJS starter kit, and saw that the difference were particularly in Webpack. However, downgrading Webpack to v1 does not work with the last React required in the particular project. 

Any thoughts? Many thanks :)

**Comment by bschellekens** [comment]
Yes, saw the project but that was build in a previous ReactJS version with webpack 1.14. It seems that updating this to webpack 3 generates the issue as well.
What's your experience there?

**Comment by dmitrykurmanov** [comment]
@bschellekens we will check it.

**Comment by bschellekens** [comment]
Cool!
Is there something I can do to assist?

**Comment by dmitrykurmanov** [comment]
@bschellekens hello! I've updated https://github.com/surveyjs/surveyjs_react_quickstart repo with latest "create-react-app" and it looks ok for me. Could you check it please?

**Comment by sumitlearnt** [comment]
This is issue is still not solved , worked for older webpack version

**Comment by dk981234** [comment]
Hello, 
I think it's conflict between react-scripts and webpack.
We adding react-scripts as dependency and it installs required version or webpack.
Thanks
Dmitry
SurveyJS Team

**Comment by sumitlearnt** [comment]
So, what is the solution for this?

**Comment by dk981234** [comment]
Hello, 
You can delete your webpack from package.json and from node_modules in working directory.
Here is  [issue](https://github.com/facebook/create-react-app/issues/5972) on create-react-app github.
Thanks
Dmitry
SurveyJS Team
