### ISSUE TITLE
Jquery Datepicker localization (date format)

### ISSUE THREAD

**Issue by jerome-lemaire** [surveyjs/widgets#61]
### Are you requesting a feature, reporting a bug or ask a question?
Bug : dateformat is not working

### What is the current behavior?
dateformat is still mm/dd/yy

### What is the expected behavior?
Date format should be dd/mm/yy

### How would you reproduce the current behavior (if this is a bug)?
See the link below

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
https://plnkr.co/edit/TV1reEijMIX8WdwV6KH1?p=preview

### Specify your

* browser: Google chrome
* browser version: 67.0.3396.87
* surveyjs platform (angular or react or jquery or knockout or vue): jquery
* surveyjs version: 1.0.26

**Comment by tsv2013** [comment]
The default value from widget overrides datepicker behaviour

**Comment by jerome-lemaire** [comment]
Thank you but there is another issue :

At line 46:
`pickerWidget.datepicker("setDate", new Date(question.value));`

This is not working because `question.value` can be 30/06/2018 (if I've set dateformat to dd/mm/yy) and `new Date("30/06/2018")` will fail

**Comment by tsv2013** [comment]
Can you check the referenced commit?

**Comment by jerome-lemaire** [comment]
It works like a charm

Thank you.
