### ISSUE TITLE
select2 - deselect the chosen option and leave the field empty

### ISSUE THREAD

**Issue by rekotc** [surveyjs/widgets#62]
Hi,
is it possible, in a select2, to deselect the chosen option and leave the widget empty?

thanks in advance

**Comment by tsv2013** [comment]
Select2 custom widget has the `select2Config` option:
```JSON
            "select2Config": {
              "allowClear": true,
              "placeholder": "Choose country..."
            },
```
This option allows to pass any settings to the select2 control.
Here is the example of the custom config with the `select2Config` option - https://embed.plnkr.co/r8zspi/

**Comment by rekotc** [comment]
that's perfect! Thanks!
