### ISSUE TITLE
I'd like to implement a custom static widget

### ISSUE THREAD

**Issue by padcom** [surveyjs/widgets#65]
In my implementation of Survey.js I need to implement a header for some of the parts of the survey.

I figured so far there is an HTML widget that I can use for that occasion but repeating the same thing over and over again in a long survey seems a bit not DRY.

Therefore I wanted if there is an option, without extending the survey editor, to incorporate a custom static control in the survey?

**Comment by tsv2013** [comment]
Probably you can use the [onAfterRenderPage](https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderPage)or the [onAfterRenderQuestion](https://surveyjs.io/Documentation/Library/?id=surveymodel#onAfterRenderQuestion) event to solve your task.

Here is the example - https://surveyjs.io/Examples/Library/?id=survey-afterrender&platform=jQuery&theme=default

**Comment by padcom** [comment]
I found a better way:

1. As I am using Vue I have included the vue-custom-element plugin and converted my static html into a custom element
2. Using the HTML widget in Survey.js builder I have added that to the page

That solves my problem.

**Comment by padcom** [comment]
I can even parameterize my custom html and make it reusable :)
