### ISSUE TITLE
Unable to get Datepicker with Icon trigger

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/widgets#66]
Cloned from https://github.com/surveyjs/surveyjs/issues/1206
@ashygk

### Are you requesting a feature, reporting a bug or asking a question?
Question/Feature

### What is the current behavior?
I am able to include datepicker using custom widgets from SuveyJS in my Angular5 application

### What is the expected behavior?

I would like to know if we have an option for datepicker to be displayed on an icon trigger
https://jqueryui.com/datepicker/#icon-trigger

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

### Specify your

* browser: Chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue): Angular 5
* surveyjs version: 1.0.25

**Comment by tsv2013** [comment]
We need to add a custom config option for the datepicker custom widget

**Comment by tsv2013** [comment]
I've added the `config` property to set the datepicker options, e.g.
```JSON
      {
        name: "date",
        type: "datepicker",
        inputType: "date",
        title: "Your favorite date:",
        dateFormat: "mm/dd/yy",
        config: {
          showOn: "button",
          buttonImage:
            "https://jqueryui.com/resources/demos/datepicker/images/calendar.gif",
          buttonImageOnly: true,
          buttonText: "Select date"
        },
        isRequired: true
      },
```
The feature will be available in the next update, most likely tomorrow.

**Comment by ashygk** [comment]
@tsv2013  Thank you so much :)

**Comment by ashygk** [comment]
The datepicker with icon trigger works fine separately, but not if included as a column in matrix dynamic

**Comment by ashygk** [comment]
`        SurveyJson: {
            pages: [
                {
                    name: "page1",
                    elements: [
                        {
                            type: "matrixdynamic",
                            name: "ComplexMedicalNeeds",
                            titleLocation: "hidden",
                            columns: [
                                {
                                    name: "Date",
                                    cellType: "datepicker",
                                    dateFormat: "mm/dd/yy",
                                    config: {
                                        showOn: "button",
                                        buttonImage:
                                        "https://jqueryui.com/resources/demos/datepicker/images/calendar.gif",
                                        buttonImageOnly: true,
                                        buttonText: "Select date"
                                    },
                                    inputType: "date"
                                },
                                {
                                    name: "Narrative",
                                    cellType: "comment"
                                }
                            ],
                            cellType: "datepicker",
                            rowCount: 0,
                            addRowLocation: "top",
                            addRowText: "ADD COMPLEX NEED  +",
                            removeRowText: "DELETE"
                        }
                    ]
                }
            ],
            showTitle: false,
            showQuestionNumbers: "off",
            questionErrorLocation: "bottom"
        }`

**Comment by ashygk** [comment]
Also, not able to add row count to comment column(Narrative)

**Comment by ashygk** [comment]
@tsv2013 / @andrewtelnov  Please see above questions I have

**Comment by tsv2013** [comment]
@ashygk The last questions are not related to the original one. I'll extract them into separate threads. Could you please post new questions into separate threads - it will be easy to find answers fo other members of the community. Thanks.
