### ISSUE TITLE
Datepicker with icon trigger not displayed in matrixdynamic question

### ISSUE THREAD

**Issue by ashygk** [surveyjs/widgets#68]
The datepicker with icon trigger works fine separately, but not if included as a column in matrix dynamic
`SurveyJson: { pages: [ { name: "page1", elements: [ { type: "matrixdynamic", name: "ComplexMedicalNeeds", titleLocation: "hidden", columns: [ { name: "Date", cellType: "datepicker", dateFormat: "mm/dd/yy", config: { showOn: "button", buttonImage: "https://jqueryui.com/resources/demos/datepicker/images/calendar.gif", buttonImageOnly: true, buttonText: "Select date" }, inputType: "date" }, { name: "Narrative", cellType: "comment" } ], cellType: "datepicker", rowCount: 0, addRowLocation: "top", addRowText: "ADD COMPLEX NEED +", removeRowText: "DELETE" } ] } ], showTitle: false, showQuestionNumbers: "off", questionErrorLocation: "bottom" }`

**Comment by ashygk** [comment]
Also, not able to add row count to comment column(Narrative)
![capture](https://user-images.githubusercontent.com/36975459/42383115-f06ab812-80fb-11e8-8cce-a52cef439c76.PNG)

**Comment by tsv2013** [comment]
@ashygk Are there separate issues?
Please check 
https://github.com/surveyjs/widgets/issues/67
https://github.com/surveyjs/widgets/issues/69

**Comment by ashygk** [comment]
Separate issues happening in one matrix dynamic question..anyways you can disregard this as you created new ones

**Comment by tsv2013** [comment]
@ashygk ok, thank you for the clarification :-) don't worry, we are here
