### ISSUE TITLE
Not able to add row count to comment column(Narrative)

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/widgets#69]
![image](https://user-images.githubusercontent.com/3013415/42383123-fff47ed8-813e-11e8-856c-6d11032cf095.png)

**Comment by tsv2013** [comment]
Extracted from the https://github.com/surveyjs/widgets/issues/66
Originally opened by @ashygk

**Comment by ashygk** [comment]
I am trying to add a 'Comment' question as one of the columns in matrix dynamic. But i am not able to edit the rowCount of the Comment question

**Comment by tsv2013** [comment]
It's a bug on our side. I've fixed it via commits referenced above. Fix will be available in the nearest update.

**Comment by ashygk** [comment]
There are few other properties of comment question that do not work when included in matrixdynamic. (maxLength property)
