### ISSUE TITLE
Widgets cannot be imported/used with Angular CLI and TS 2.7.x

### ISSUE THREAD

**Issue by halexiev-hedgeserv** [surveyjs/widgets#71]
Hi @andrewtelnov, @tsv2013,

As shown in my last comment here:

https://github.com/surveyjs/surveyjs/issues/1195

widgets do not seem to work when used with angular cli and typescript 2.7.x.

Am I doing something wrong, can you please have a look?

Thanks,
Hristo

**Comment by dmitrykurmanov** [comment]
Hello! Could you please check our https://github.com/surveyjs/surveyjs_angular_cli repo? Thanks.

**Comment by dmitrykurmanov** [comment]
May be the problen with typrscript version. We need to use 2.7 in our **surveyjs_angular_cli**

**Comment by dmitrykurmanov** [comment]
@halexiev-hedgeserv I've updated typescript in **surveyjs_angular_cli** to the latest version ("^2.9.2") and it looks ok, could you please check it . Or you are welcome to share your example with the bug.
