### ISSUE TITLE
SortableJS duplicating component when data is set

### ISSUE THREAD

**Issue by johnjcorcoran** [surveyjs/widgets#72]
**Steps to replicate**

We are attempting to pre-populate a sortable-JS question with existing data (answers/choices), based on this ReactJS approach:
https://surveyjs.io/Examples/Library/?id=survey-data&platform=Reactjs&theme=default

The data looks like this, which is the data that the library outputs when the question is answered:
`"priorities": [ "priority1", "priority2" ]`

The markup is duplicated, one after the next: one has the default choices, and the other has the data that we are populating the question with.

**Expected behaviour**

The surveyJS-based question appears just once, with the choices populated by the data provided.

**Browsers replicated in** 

Firefox, Chrome.

**Comment by dmitrykurmanov** [comment]
@johnjcorcoran hello! I've created an example for you: https://plnkr.co/edit/ORWVd4OTPYrg8XtEiCfd?p=preview I think it looks ok. Could you please check it and modify if you need?

**Comment by johnjcorcoran** [comment]
Sorry for the delayed confirmation - I've been away. Your solution helped me fixed the issue, which was on our side. 

Many thanks, John
