### ISSUE TITLE
How to add field validation to inputmask

### ISSUE THREAD

**Issue by yidan** [surveyjs/widgets#74]
Is there a way to use inputmask for currency together with numerical validation? Say, shows an error message when the user input an amount smaller than 100? Also, is there a way to remove the mask before submitting? 
I do see these functionalities are available in the inputmask repo (min and "removeMaskOnSubmit"), but I'm not sure how to use them in the surveyjs widget. 
https://surveyjs.io/Examples/Library/?id=custom-widget-inputmask&platform=jQuery&theme=default

**Comment by tsv2013** [comment]
Sorry for late response.
I'm afraid the `removeMaskOnSubmit` will not work in our case. According the https://github.com/RobinHerbots/Inputmask docs, it works on form submit only.
I'll try to prepare a sample for you.

**Comment by tsv2013** [comment]
I've found another option - https://github.com/RobinHerbots/Inputmask#autounmask
I've set this option by default for the inputmask custom widget
This fix will be available in the next minor update, most likely in a couple of days

After that you can use simple numeric range validator:
```JSON
        {
            "type": "text",
            "inputMask": "currency",
            "name": "currency",
            "title": "Currency:",
            "validators": [
              {
                  "type": "numeric",
                  "minValue": 10,
                  "maxValue": 10000
              }
            ]
        }
```

**Comment by ahsan2882** [comment]
how does validation work for phone numbers?
I want to show error if the phone number is missing a digit
