### ISSUE TITLE
custom widget in react is showing old value.

### ISSUE THREAD

**Issue by abdul-qadir** [surveyjs/widgets#81]
We are using text like custom widget for numeric values. This widget is added in panel dynamic with other standard dropdown fields. Removing second row is removing(updating) values of dropdown fields i.e. having values of 3rd row but not of custom widget field. Custom widget value is updated in react component state but not rendered in UI. how can we fix this

**Comment by abdul-qadir** [comment]
https://plnkr.co/edit/SAaQN1iCPKvT72ECxZkZ?p=preview
This widget is used in paneldynamic with other dropdown fields.
@tsv2013

**Comment by tsv2013** [comment]
This is the full plunker to reproduce the issue - https://plnkr.co/edit/9cIZ0iSNhYM7v0lQ0uIh?p=preview

**Comment by dmitrykurmanov** [comment]
We've fixed the issue via the https://github.com/surveyjs/surveyjs/commit/6730d0a536eaf21812458e9c86b3f7402a70f68c. Fix will be available in the next minor update.

@abdul-qadir thank you for the reporting!
