### ISSUE TITLE
Cannot load widgets?

### ISSUE THREAD

**Issue by lukasmedia** [surveyjs/widgets#83]
Im using Surveyjs without any errors.
If i include the widgets as CDN
<script src="https://surveyjs.azureedge.net/0.95.0/surveyjs-widgets.min.js"></script>
The icons do appear in the editor. 
If i click one i get a minified version of the widget (the smileys only a dropdown shows) and i get the error:

knockout-min.js:73 Uncaught TypeError: Unable to process binding "if: function(){return row.koVisible }"

Any idea?

**Comment by lukasmedia** [comment]
It seems i'm missing a lot of of css files (https://unpkg.com/jquery-bar-rating@1.2.2/dist/themes/bars-1to10.css). Also the order of including (js,css) is important.

Fixed for now, but i would be nice to have a working example

**Comment by tsv2013** [comment]
You can find examples here - https://surveyjs.io/Examples/Library/?id=custom-widget-select2-tagbox&platform=jQuery&theme=default
