### ISSUE TITLE
Widgets incompatible with IE11

### ISSUE THREAD

**Issue by harpsicord86** [surveyjs/widgets#84]
Trying to use the surveyjs widgets to use pretty-checkbox and I'm getting the following error using this on IE11:

Exception was thrown at line 1543, column 11 in http://localhost:52136/node_modules/surveyjs-widgets/surveyjs-widgets.js

0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'values'

If there is a handler for this exception, the program may be safely continued.

As I understand it, older versions of browsers don't support this.  Can we not include a fix for this just to cater for slightly older browsers?  Thanks

**Comment by dmitrykurmanov** [comment]
@harpsicord86 thank you for the reporting! The problem in the pretty checkbox library. This library does not support IE because of using Object.values. You can fix it via the polyphil:

```js
// polyphil for ie
if (!Object.values)
  Object.values = function(object) {
    return Object.keys(object).map(function(key) {
      return object[key];
    });
  };
```

and I will add the code above to the example on our site
