### ISSUE TITLE
Sortablejs Widget Question

### ISSUE THREAD

**Issue by rachel-flux** [surveyjs/widgets#85]
When I visit the [sortable website](http://rubaxa.github.io/Sortable/) and view their examples, the list items all sort within the list.  But within the SurveyJS flow, you need to drag each item into a separate results box.

During user testing, our users consistently re-order within the lower section but never drag the items into the top results box.  So I'm wondering if there is a surveyJS flag or option that exists to not render a separate results box?

The current functionality allows you to select which items to include while ranking.  But in our case, the users need to rank all items.

**Comment by tsv2013** [comment]
You can use the CSS to hide source:
```CSS
.sjs-sortablejs-source {
  display: none;
}
```
and the following code to fill results at the start:
```JS
survey.getAllQuestions().forEach(function(q) {
  if(q.getType() === "sortablelist") {
    q.value = q.choices.map(function(c) { return c.value; });
  }
});
```

as shown in this example - https://plnkr.co/edit/bhAMb2zx5QExhMgGmjqd?p=preview

**Comment by rachel-flux** [comment]
Thank you for your quick help!  This is exactly what I was trying to accomplish.
