### ISSUE TITLE
Locale bug when using nouislider in SurveyJS builder

### ISSUE THREAD

**Issue by lukasmedia** [surveyjs/widgets#86]
In SurveyJS builder; add a new nouislider to your survey.
Select it, on the right hit "edit" from "pipsValues". In the popup add some value/text items. All fine.
Verify the "pipsValues" options are stored in the JSON by clicking JSON editor.

Now in the survey properties; hit locale and change to another language. 
Verify the  "pipsValues" options are lost.

You have to start over and dont change the language.

**Comment by tsv2013** [comment]
I've fixed the issue (actually there was an issue in SurveyJS core library)
Fix will be available in the nearest update

**Comment by tsv2013** [comment]
Just for memory - plunker to check and play with - https://plnkr.co/edit/HxSI1vTcoOp9piCGtyDt?p=preview

**Comment by lukasmedia** [comment]
I cannot play with the plunker, for sure beause the .js is 404: https://surveyjs.azureedge.net/1.0.50/survey.ko.js

**Comment by tsv2013** [comment]
@lukasmedia Absolutely right - I leaved this link here "Just for memory" and "Fix will be available in the nearest update"
Sorry for misunderstanding

**Comment by lukasmedia** [comment]
Just tested with https://surveyjs.azureedge.net/1.0.52/surveyeditor.js and no improvement, but things got worst: when i switch to json / designer the all values are lost.

**Comment by tsv2013** [comment]
Yes. The bug is not fixed yet. We're working on the fix. Once it will be fixed we'll update this thread.
Sorry for possible inconvinience.

**Comment by dmitrykurmanov** [comment]
@lukasmedia We've fixed the bug. 

Please check the example with a new library build: https://plnkr.co/edit/4BPtn4ssKvq46C4we5SV?p=preview    

Fix will be available in the next minor update.
