### ISSUE TITLE
iCheck widget console errors

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/widgets#87]
from @NafanyaVictorovna: 

> if you meant json - it's ordinary radio buttons (more than 2 cases)
I have long complicated assessment, with several pages and for each question with radio/checkbox buttons choice (where are more than 2 cases) I have that problem:
when I select answer first time i had error:
Uncaught Error: Syntax error, unrecognized expression: input[value=myValueName] in icheck file.
I downloaded files from icheck github, and use icheck.min.js.
So, here is the example with json.
Please, look at the matrix https://plnkr.co/edit/RYYF8txxUtG5Au79IgFB?p=preview
But I haven't problems with matrix on my view, just with checkboxes and radio. Also, when the error is, and I change tab radio/checkbox buttons are absent in several fields by random.

**Comment by dmitrykurmanov** [comment]
@NafanyaVictorovna fixed via the https://github.com/surveyjs/widgets/commit/cced25a6d111d8e35d47c5b1cf66bf144b72d5a2. Fix will be available in the next minor update. 

Also please check the example with updated widget: https://plnkr.co/edit/qIepsFt9IjuPUIdkFW1a?p=preview

**Comment by dmitrykurmanov** [comment]
@NafanyaVictorovna most likely today.

**Comment by NafanyaVictorovna** [comment]
@dmitrykurmanov 
So, the fix didn't help to resolve the problem.

**Comment by dmitrykurmanov** [comment]
@NafanyaVictorovna Are the errors gone? If yes but you have another problem, please create a new issue. It would be great if it will contain the example. May be we need to clarify steps to reproduce. Thank you.
