### ISSUE TITLE
Barrating widget updates are not stored correctly

### ISSUE THREAD

**Issue by chambleton** [surveyjs/widgets#91]
Hi - I found an issue with the barrating control in which I have several different questions along with a barrating. I would watch the answers being set from onValueChanged and what would happen is that as soon as i selected an item from barrating, it would overwrite several of the other answers. However, upon save() the answers would come back in the set but the one for the barrating would not. 

What was happening is that this control is based upon the "dropdown" and would call the handleOnChange() to set the question value in its state. However, when the value is set by clicking on a star ($el.barrating("set", question.value);), the jquery-barrating calls change() on the select element, but the QuestionDropDown.handleOnChange() isn't called -- the event needs to be explicitly fired (see below the comment). Hopefully this will save someone a few headaches!
```
    afterRender: function (question, el) {
      var theEl = el;
      var $el = $(el).is("select") ? $(el) : $(el).find("select");
      var isUpdating = false;
      // update the values 
      var updateValueHandler = function () {
        if (!isUpdating) {
          $el.barrating("set", question.value);
        }
      };

      // tell the barrating library to render our stuff!      
      $el.barrating("show", {
        theme: question.ratingTheme,
        initialRating: question.value,
        showValues: question.showValues,
        showSelectedRating: false,
        onSelect: (value, text) => {
          isUpdating = true;
          question.value = value;

          // IMPORTANT!! Manually dispatch the event to the dropdown to trigger handleOnChange in SurveyJS!
          // if handleOnChange() is not called, the question store gets corrupted!
          var event = new Event('input', { bubbles: true });
          var select = theEl.getElementsByTagName("select")[0];
          select.dispatchEvent(event);
          isUpdating = false;
        }
      });
      question.valueChangedCallback = updateValueHandler;
      updateValueHandler();
    },
    willUnmount: function (question, el) {
      var $el = $(el).is("select") ? $(el) : $(el).find("select");
      $el.barrating("destroy");

      question.valueChangedCallback = null;
    }
```

**Comment by dmitrykurmanov** [comment]
Hello! Thank you for the contributing! 

We've checked your code and don't fully understand the root of the problem.

Could you please provide a plunker or json to reproduce the bug?

**Comment by chambleton** [comment]
Hi - I can try to put together a plunker but the easiest way to reproduce it is to set a browser breakpoint in QuestionDropDown.handleOnChange() and then click a star in the widget. You'll see that the breakpoint is never hit, which messes up the state. However, if you then add in the code I mentioned above and try it again, you'll see that the breakpoint is hit and the state is no longer out of sync with the jquery-barrating component.

**Comment by tsv2013** [comment]
@chambleton I'm sorry but the code you've sent doesn't belong to the https://github.com/surveyjs/widgets/blob/master/src/jquery-bar-rating.js repository. We'll be happy to investigate the issue on the minimal live sample (plunker or other sanbox). Thanks for understanding.

**Comment by tsv2013** [comment]
@chambleton Another way - you can provide us with exact steps how to reproduce the issue on our demos or samples.
