### ISSUE TITLE
Emotions rating missing

### ISSUE THREAD

**Issue by dhwanivora** [surveyjs/widgets#92]
I am using surveyjs with angular and the files for emotions rating widget seem to be missing and that question does not show up at all in the final survey.

**Comment by dmitrykurmanov** [comment]
Hello! Thank you for the reporting. Could you please check the example: https://plnkr.co/edit/97jZr34bhXnOwxgS2ZuV?p=preview It looks ok for me

**Comment by gurix** [comment]
Sample is not working anymore.

**Comment by andrewtelnov** [comment]
@gurix Please use [the following example](https://surveyjs.io/Examples/Library/?id=custom-widget-emotionsratings).

Thank you,
Andrew
