### ISSUE TITLE
Include Bootstrap widget in build

### ISSUE THREAD

**Issue by willgdjones** [surveyjs/widgets#95]
### Are you requesting a feature, reporting a bug or asking a question?
Requesting a feature

### What is the current behavior?
I would like to use the Bootstrap Datepicker, which seems to be available in the widgets src.
https://github.com/surveyjs/widgets/tree/master/src

### What is the expected behavior?
I can't seem to be able to import the bootstrap datepicker in the Survey Editor with e.g.

```
widgets.bootstrapdatepicker(SurveyKo);
```

It seems like it is not exported in the https://github.com/surveyjs/widgets/blob/master/webpack.config.js file - so should be a straightforward fix.

**Comment by dmitrykurmanov** [comment]
I've added the `bootstrapdatepicker` widget to the build. 

As for your local error, could you please try to use `"type": "bootstrapdatepicker",`

**Comment by willgdjones** [comment]
Unfortunately using `"type": "bootstrapdatepicker",` doesn't change the error

**Comment by dmitrykurmanov** [comment]
I've created an example with latest widgets build and it works as expected for me : 
https://plnkr.co/edit/ULr0gu2rXYD0uiq8yGNg?p=preview

Could you please check it?

**Comment by willgdjones** [comment]
Hi @dmitrykurmanov - I do see that this work well, but I don't immediately see how to translate that into my development environment. Also - there seems to be a large amount of external CDN scripts that makes it hard to see what I need to include myself. Is it possible to look at an example with codesandbox?

**Comment by willgdjones** [comment]
I will try to build it myself but it could take a while.

**Comment by dmitrykurmanov** [comment]
@willgdjones  I am not sure, that `bootstrapdatepicker` works as es6 module. So could you please try to add it as script tag  into your `index.html`?
