### ISSUE TITLE
Slow autocomplete

### ISSUE THREAD

**Issue by willgdjones** [surveyjs/widgets#97]
### Are you requesting a feature, reporting a bug or asking a question?
Asking a question

### What is the current behavior?
I have around 5000 items, and I am using the Tagbox question: https://surveyjs.io/Examples/Library/?id=custom-widget-select2-tagbox&platform=jQuery&theme=default. The autocomplete functionality is very slow.

### What is the expected behavior?
I would like the view that autocomplete options quicker, as it is too slow to be useable at the moment. A solution could be to add a minLength parameter to only initialise the Select2 plugin after the user has typed in 3 characters, but I'm not sure where to set this is a configuration parameter. Another option could be to only start the search after 1 second since the users last key stroke.

### How would you reproduce the current behaviour (if this is a bug)?
Change the list in the example to a list that has 5000 items. https://surveyjs.io/Examples/Library/?id=custom-widget-select2-tagbox&platform=jQuery&theme=default

* surveyjs platform Vue
* surveyjs version: 1.0.59

**Comment by tsv2013** [comment]
@willgdjones This code can't be pasted to the editor due to contains JavaScript functions code. I've pout this code into live SurveyJS live sample and it works ok for me - https://next.plnkr.co/edit/DaKyiCYjykdF3d43

**Comment by willgdjones** [comment]
Ok - that makes sense. I guess I will just have to change things on my application as I have been storing the survey definitions themselves as JSON, and will need to save them in a different format if it actually contains javascript.
