### ISSUE TITLE
Nouislider doesn't fit

### ISSUE THREAD

**Issue by budupaul** [surveyjs/widgets#99]
### Are you requesting a feature, reporting a bug or asking a question?

Reporting a bug

### What is the current behavior?

When adding a nouislider question, in the right of the  question a small scrollbar appears because the question doesn't fit in the container (regarding height)

### What is the expected behavior?

Have a way to make the question's height smaller or fit the nouislider. Is this possible?

**Comment by dmitrykurmanov** [comment]
@budupaul Hello! This is custom widgets issue, so I've transferred it. We need to fix it. As a workaround you can use dirty "!important" css rule.

```css
.noUi-target {
    margin-bottom: 60px !important;
}
```

Here an example of the workaround: https://plnkr.co/edit/r8bRUUmfcHSVfemQaPrz?p=preview

**Comment by dmitrykurmanov** [comment]
@budupaul fixed via the https://github.com/surveyjs/widgets/commit/427b410d506c254301a8bb4aedc8d249c6445131 Fix will be available in the next minor update.
